Feature: 네트워크 모듈 구현
depromeet/WalWal-iOS pull request #1
Opened 2024-06-27 06:39 UTC by Zoe0929

## 📌 개요
`RxAlamofire`를 이용해 네트워크 계층 함수화를 진행했습니다.

## ✍️ 변경사항
- Network 계층에 네트워크를 위한 기본 세팅을 진행했습니다. 
- 회의 시간에 의견 주신 파라미터 관련 함수 추가 구현했습니다
- RxAlamofire를 바탕으로 Single 타입을 반환하는 request 함수 구현했습니다. 
- 반복해서 사용되는 필드를 BaseResponse를 사용하여 단순화했습니다. 사용할 때는 아래와 같이 사용해주시면 됩니다
``` swift
func getUserInfo() -> Single<BaseResponse<UserDTO>
```
- 폴더링 기준에 맞는지 확인해주시면 감사하겠습니다!

## 📷 스크린샷
없습니다. 

## 🛠️ **Technical Concerns(기술적 고민)**
### RxAlmofire vs Almofire + async await
처음에는 async await 기반으로 작성했었으나, RxAlmofire를 택하게 되었습니다. async await로 처리된 결과를 Task로 묶어서 다시 mutation에 넘기는 것이 불필요하다 느꼈습니다. 그렇기 때문에 상태 변화를 쉽게 관리할 수 있는 RxAlmofire를 선택했습니다. 관련하여 의견 남겨주시면 감사하겠습니다 :)

### Single<T> vs observale<T>
request의 결과를 처리해줄 때 Single을 사용했습니다.
Observable은 전송된 데이터를 관찰하는 관찰자 클래스, 즉 데이터가 전송되는 것을 계속 감지하고 있습니다.
API 통신 시에 데이터를 request 후 응답 받은 후에는 관찰의 필요성이 적어지고, 메모리 낭비로 인해 dipose 를 직접 해줘야 합니다. 하지만, Single을 사용하면 데이터를 한번만 받기 때문에 dispose 를 직접해주지 않아도 돼서 Single을 사용하는 것이 더 적합하다고 판단했습니다.
프로젝트 내에서 실시간 데이터 업데이트, 무한 스크롤등의 기능을 구현하기 위해서는 observable<[T]>를 사용해야 할 것 같은데, 이걸로 변경하는 게 좋을지, 두개 다 작성하여 필요에 따라 사용하는 것이 좋을지 고민됩니다! -> 네트워크 관련은 single로 처리하는 게 좋다는 의견

[참고자료]
[observable vs Single](https://sodp2.tistory.com/14)
[observable vs Single](https://devming.medium.com/single-vs-observable-70b0a504c083)
[Single](https://velog.io/@dev_jane/Traits-Single%EA%B3%BC-Completable)

2024-06-30 11:56 UTC, kimkyunghun3 requested changes
고생했습니다!! 전체적으로 깔끔하게 주석도 잘해주셔서 읽기 편하고 좋았어요~!
리뷰는 모두 정답이 없을 수 있어서 언제든 논의 환영입니다🤗

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +extension Encodable {
여기에 사용하는 함수가 이곳에 종속으로 사용되나요? 아니면 다른 곳에서 사용되나요?
그에따라 파일 만들거나 파일 종속 extension 등으로 바뀔거같아요!

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +import Alamofire
요거 컨벤션 상 써드파티랑 구분 개행 필요할거같아요!

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
여기랑 다른 곳 모두 return 에 대해 한줄 개행에 대해 논의를 같이해볼까요~?

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Interface/NetworkService.swift
> +enum NetworkError: Error {
에러를 전체 관리할 수 있는 곳이 있으면 좋을거 같아요
ex) enum으로 각 성격에 맞는 에러로 분리하는 작업
지금은 네트워크 에러만 생각할테지만, 추후에 로그인 등에 대해서도 에러 처리를 해야되는데
에러 처리가 한곳으로 모아져 있어서 관리되면 더 좋을거같아요

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Interface/EmptyResponse.swift
> +public struct EmptyResponse: Decodable {}
Data가 없는 경우가 언제이며, 언제 이것을 사용해야되나요~?

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Interface/APIEndpoint.swift
> +enum RequestParams {
이 요청 파라미터는
파라미터가 없는 구조(plain), upload 부분도 모두 대응이 되는 건가요?

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +class NetworkService: NetworkServiceProtocol {
NetworkService를 클래스로 만든 이유가 궁금해요!
final 이 안붙어있는거 상속여부가 있는걸까요?

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
이 친구는 보통 언제 체크하면좋을까요~?
제 생각에는 보통 서버 요청하는 request에서 체크할거같은데, 지금 작성해주신 예시로는 외부에서 사용하는 느낌이 들어서요!
어떻게 생각하는지 궁금해요!

2024-06-30 11:56 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +    /// weatherUsecase.getWeather()
사용 예시가 useCase의 호출 메서드를 적어두신거같아서 헷갈려요!
이 request 메서드를 사용하는 법을 적어주시는게 더 명확해보여요!

2024-07-01 03:07 UTC, ji-yeon224 commented
고생하셨습니다! 주석이 많아서 사용할 때 도움이 될 것 같습니다~😊

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Interface/APIEndpoint.swift
> +    var headers: [String: String]? { get }
`typealias HTTPHeaders = [String: String]` 이런식으로 typealias를 사용해서 처리하는게 시각적으로는 좋을 듯?

추가적으로, 굳이 옵셔널 처리 없이 [:]를 기본값으로 넣어도 될 듯 합니다 ()
`let headers = endpoint.headers != nil ? HTTPHeaders(endpoint.headers!) : nil`
여기서 크게 문제는 없겠지만, 강제 언래핑을 싫어하는 편이라,,,

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Interface/APIEndpoint.swift
> +    var headers: [String: String]? { get }
`let headers = endpoint.headers != nil ? HTTPHeaders(endpoint.headers!) : [:]`
그럼 이렇게 되겠쥬

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Interface/APIEndpoint.swift
> +}
Require query와 Require body가 같이 요구되는 케이스도 처리 되는지??

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
해당 함수 내부에 내용이 너무 많은 것 같아요.
개인적으로, 현재의 코드내용이라면
1. URL을 생성하는 함수
2. Header만드는 함수
3. Body만드는 함수를 만들어서

순차적으로 urlRequest에 대한 체이닝을 거는게 좋을 것 같아요~

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
좀 더 디테일하게 들어가면, 
1. URL생성
: baseURL지정 -> path추가 -> 쿼리파라미터 세팅 -> URL리턴

2. 메서드 세팅
: 생성된 URL을 베이스로 URLRequest생성 -> 메서드 세팅

3. 헤더 세팅
: 메서드 세팅된 URLRequest에 Header세팅함수 체이닝

4. 바디 세팅
: 헤더 세팅된 URLRequest에 Body세팅함수 체이닝

뭐 이런식으로..?

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +import Alamofire
이거 근데 RxAlamofire 임포트 하고 있는데, 따로 Alamofire를 임포트 하는 이유가 있나요?

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +class NetworkService: NetworkServiceProtocol {
저도 클래스로 만든 이유가 궁금합니다~

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Interface/NetworkService.swift
> +enum NetworkError: Error {
저도 일반적으로 에러는 따로 모아서 관리하는 편이라, 파일을 아예 나누는게 좋아보여요~
추가적으로 단순히 Error케이스만 나누는게 아니라 `LocalizedError` 를 확장해서 
`customErrorDescription`을 따로 만들어서 사용하는게 좋을 것 같아요. 그래야 특정 에러에 대한
설명을 우리가 편하게 정할 수 있겠죠??

```
struct NetworkErrorModel: Codable {
  let isSuccess: Bool
  let code: Int
  let message: String
}

public enum CustomError: LocalizedError {
  case invalidURL
  case networkError(message: String) // 네트워크 연결 불량
  case decodeError
  case strongRefError
  case unknown(message: String)
  
  public var customErrorDescription: String {
    switch self {
    case .invalidURL:
      return "해당 URL은 유효하지 않습니다."
    case .decodeError:
      return "데이터 타입을 decode 하는데에 실패하였습니다."
    case .strongRefError:
      return "Self가 nil 입니다."
    case .networkError(let message):
      return message
    case .unknown(let message):
      return message
    }
  }
}
```
저는 대충 이런식으로 사용합니다

2024-07-01 08:34 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +        /// url 생성
asURLRequest에서 작성한 코멘트와 같이, 내부 코드가 너무 긴 것 같아요!
제가 작성한 코멘트 참고해서, 내부 로직 분리를 해보면 어떨까요???
+ log를 남기는 부분은 함수로 빼는게 적절할 것 같아요

2024-07-01 09:05 UTC, usa4060 requested changes
화이팅~!

2024-07-01 09:06 UTC, usa4060 requested changes
코멘트 확인해보시구, 궁금하신 점 있으면 더 질문주세요~!~!

2024-07-01 11:51 UTC, ji-yeon224 requested changes

2024-07-01 11:51 UTC, ji-yeon224 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +        .asSingle()
flatMap에서 Single타입을 리턴하고 있는 것으로 보이는데, 이후에 `.asSingle()`로 변환 작업을 하는 이유가 있을까요?!

2024-07-01 13:28 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +extension Encodable {
네트워크에서만 사용할 것 같아서 따로 파일로 분리할 필요가 없다고 생각했습니다!

2024-07-01 13:30 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +import Alamofire
제 Xcode 문제일지는 모르겠는데, Alamofire를 따로 import하지 않으면 Alamofire의 함수들이 사용이 어려웠습니다! 
컨벤션 전체적으로 다시 한번 확인하겠습니다

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +class NetworkService: NetworkServiceProtocol {
final을 안 붙인 건 실수입니다! 바로 붙이겠습니다~

처음 NetworkService를 만들 때는 싱글톤 패턴으로 공유해서 사용하는 형태를 생각했어서 class로 만들어뒀습니다. 
구현 후에 보니 굳이 class일 필요는 없다는 생각이 드는데, 구조체로 만들었을 때의 장점이 어떤 것이 더 있을까요?!
지금 생각했을 때는 메모리상의 이점 정도 밖에 생각이 들지 않아서요! 의견 자유롭게 주시면 좋을 것 같아요

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +    /// weatherUsecase.getWeather()
오우 샘플 프로젝트의 주석을 가져오다보니 잘못된 예시를 넣어둔 것 같네요! 꼼꼼한 리뷰 감사합니다.

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +        /// url 생성
이 부분도 수정하겠습니다! 
하나의 함수에 너무 많은 동작이 있는 건 지양해야겠군요

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +        .asSingle()
원래 다른 방식이어서 수정하는 과정에서 지우는 걸 깜빡한 것 같습니다! 
꼼꼼한 리뷰 감사합니다

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
제가 생각한 용도는 맨 처음 앱에 진입했을 때, 네트워크 자체가 연결되어 있지 않으면 알럿을 띄워주는 등의 노티를  주기 위해 필요하다고 생각했습니다!

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Interface/APIEndpoint.swift
> +    var headers: [String: String]? { get }
오! 그게 더 좋을 것 같네요 반영하겠습니다!

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Interface/APIEndpoint.swift
> +enum RequestParams {
upload가 빠져 있는 것 같네요 보충하겠습니다

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Interface/APIEndpoint.swift
> +}
앗 그 부분 빠진 것 같아요! 보충하겠습니다

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Interface/EmptyResponse.swift
> +public struct EmptyResponse: Decodable {}
BaseResponse를 사용할 때 서버에서 내려주는 값 중 data 필드가 없는 경우입니다!
예를 들면, 
``` json
{
   "code" : 200,
   "sucess" : true
}
```
이렇게 간단하게 성공 여부만 내려주는 경우입니다!

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Interface/NetworkService.swift
> +enum NetworkError: Error {
좋네요! 반영해보겠습니다~

2024-07-01 19:40 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
기능 단위로 나누는 거 좋아요! 감사합니다

2024-07-02 11:06 UTC, usa4060 requested changes
코멘트 남겼습니다~ 화이팅~~ㅋㅋㅋㅋㅋㅋㅋ

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +    var headers: HTTPHeader
HTTPHeader -> HTTPHeaders로 수정하는게 좋을 듯 해요~

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        case .requestQuery(let request):
파라미터를 `let query`로 수정하는게 어떨까요??

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        case .requestWithbody(let request):
파라미터를 `let body`로 수정하는게 어떨까요??

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
query와 body를 만드는 코드의 경우 `.requestQueryWithBody`에서 중복이 되는 것 같은데
함수로 빼내서 사용하는게 가독성에 좋을 것 같다는 생각이에요~!

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +import Alamofire
아 요거 결국은 어떻게되었나요?? 둘 다 임포트하지 않으면 사용이 안되던가용?
만약 그런거면 저도 tuist에서 디펜던시 다시 확인해볼게요!

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +    /// networkService.request(endpoint: MyAPIEndpoint()).subscribe(onSuccess: { (result: MyDataType) in
EndPoint를 protocol로 선언했으니
```

enum UserEndPoint: APIEndPoint {
  case .signUp, signIn

  var method: HTTPMethod {
    switch self {
    case .signIn, .signUp:
      return .POST
    }
     , , ,
}

let endpoint = UserEndpoint.signUp
networkService.request(endpoint: endpoint).subscribe( { ,,, } )

```
이런식으로 사용해야할 것 같은데, 맞을까요???

아니면, 의도한 방식이 각 Endpoint별로 각각의 객체로 만들어서 사용하는걸 의도한걸까욥?

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +                let decodedObject = try JSONDecoder().decode(T.self, from: jsonData)
바로 받는 data를 decode하지 않고, .prettyPrinted옵션을 준 data로 가공해서 decode하는 이유가 있을까요??

추가적으로 단순히 데이터를 decode하고 encode를 함수를 따로 만들어서, Single<T>를 반환하게 하여
위의 로직내부에는 do ~ catch 구문이 안들어가도 될 것 같다는 아이디어가 떠오르네요!
```
static func decode<T: Decodable>(_ type: T.Type, from data: Data) -> Single<T> {
      do {
          let result = try JSONDecoder().decode(T.self, from: data)
          return .just(result)
      }
      catch {
          return .error(CustomError.decodeError)
      }
  }
```
예를 들면 이런??
단순한, 아이디어일 뿐이니 한번 확인만 해주세요~

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +                self.responseLogging(jsonData.toPrettyPrintedString ?? "")
만약, 단순 data가 아니라 jsonData의 메서드체이닝이 필요하다면 함수 내부에서 체이닝을 거는게 어떨까요?!

2024-07-02 11:06 UTC, usa4060 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
지희가 말 한경우 + 네트워크 통신이 발생하기 전에는 필수로 들어가면 어떨까 합니더

2024-07-02 11:21 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +    var headers: HTTPHeader
`HTTPHeaders`로 하면 Alamofire의 타입이랑 겹치는지 생성자부터 오류가 났었습니다 .. 🤔

2024-07-02 11:21 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        case .requestQuery(let request):
오호 그게 더 명확해보이기는 하네요 감사합니다!

2024-07-02 11:36 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +    var headers: HTTPHeader
ㅋㅋㅋㅋ 나쁜 알라모파이어,,,,

2024-07-02 23:35 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +class NetworkService: NetworkServiceProtocol {
@Zoe0929 말씀해주신 것처럼, class vs struct 에 대한 선택에 대해서는 여러 요소가 있을 거 같은데,
NetworkService의 특징에 대해 살펴보면 좋을거같아요
지금 말씀해주신거에서 굳이 class일 필요가 없다는게 어떤 부분에서 생각하시게 된건지?에 대한 궁금증도 있고요
클래스로 했을때 이유가 명확하면 해도될거같긴한데,
제 생각에서는 이 NetworkService를 보았을 떄 단순히 데이터 전송, 변환 등만 하는 거 같아서 데이터를 동적관리하는게 아닌거같아서 구조체로 해도 무방해보입니다

2024-07-02 23:36 UTC, kimkyunghun3 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
@Zoe0929 @usa4060  좋은거같습니다 그렇게 하시죠~!

2024-07-02 23:38 UTC, kimkyunghun3 commented on WalWal/Network/Interface/NetworkService.swift
> +enum NetworkError: Error {
에러 통합 음 WalWalError -> WWError..? 머 이런식으로 통합관리하는 곳으로 해서
enum case가 확장성 있게 하면 될거같습니다.
Network
Login 등등

2024-07-03 03:49 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
@usa4060  이렇게 나누려고 하다보니 함수 단위가 한줄 씩으로 쪼개지는 경우가 발생해서 고민이 되네요! 한 줄씩이어도 기능별로 나누는 게 좋을까요?

2024-07-03 04:04 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +    /// networkService.request(endpoint: MyAPIEndpoint()).subscribe(onSuccess: { (result: MyDataType) in
네 맞습니다! 
아래와 같이 사용하는 걸 생각했습니다

``` swift
@frozen
enum OnboardingEndpoint {
    case postTokenChange(_ dto: KakaoLoginRequestDTO)
    ...
}

extension OnboardingEndpoint: APIEndPointE {
 ...
}
```

2024-07-03 05:54 UTC, usa4060 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
@Zoe0929 네 저는 그래도 기능별로 나누는게, 나중에 알아보기에도 쉬울 것 같아요

2024-07-03 06:56 UTC, Zoe0929 commented on WalWal/Network/Interface/NetworkService.swift
> +enum NetworkError: Error {
오호,, 지금은 일단 파일 분리 정로도 수정했습니다!  [9ff51e7](https://github.com/depromeet/WalWal-iOS/pull/1/commits/9ff51e7bd48ad44aa6b65975e18d4916e27c108e)

2024-07-03 07:10 UTC, Zoe0929 commented on WalWal/Network/Implement/APIEndpointImpl.swift
> +        return urlRequest
@usa4060 아하! 그런 의도라면 저도 완전 찬성입니다!

2024-07-03 07:17 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +class NetworkService: NetworkServiceProtocol {
@kimkyunghun3 오호 사실 명확한 이유는 떠오르지 않아서 struct로 수정하겠습니다 :) 감사합니다!

2024-07-03 11:26 UTC, Zoe0929 commented on WalWal/Network/Implement/NetworkServiceImpl.swift
> +                let decodedObject = try JSONDecoder().decode(T.self, from: jsonData)
여기서 `.prettyPrinted` 이 옵션을 사용한 건 단순히 로그를 print할 때 조금 더 편하게 보기 위해서 였습니다! 그런데 로그를 찍기 전에 .prettyPrintString 함수 안에서 처리해주니까 굳이 데이터 가공해서 decode할 필요가 없어보이네요!

함수화 진행해서 https://github.com/depromeet/WalWal-iOS/pull/1/commits/00891ddc6f2232a6e86e19adb6d774537d1571e2 에 올려뒀습니다! 감사합니다

2024-07-05 01:58 UTC, usa4060 requested changes

2024-07-05 01:58 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/APIEndpointImpl.swift
> +            urlRequest.url = try configureQueryParams(url: url.appendingPathComponent(path), query: query)
실제 메서드 내부에서 URL을 생성하지 않고, 
파라미터로 URL을 생성해서 주입하는 이유가 있을까요??

APIEndpoint의 extension이면 메서드 내부에서 path접근이 가능할 것 같아서요!

2024-07-05 04:28 UTC, kimkyunghun3 requested changes
재요청!

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/APIEndpointImpl.swift
> +
여기 공백 혹시 깃헙에서만 보이는건가요?? 아니면 수정부탁해요~

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    func upload<T: Decodable>(endpoint: APIEndpoint, data: [UploadData]) -> Single<T> {
요기는 public 이 아닌 이유가있나요?

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +
요기 공백도

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +
요기도 혹시 공백이..?!

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +        return prettyPrintedString as String
이거 혹시 옵셔널 String으로 반환하는데 타입캐스팅 String해서 String으로 바꾸는건 옵셔널 String을 사용 안하는건가요?!
코드 설명 부탁드려요!

2024-07-05 04:28 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
이거 혹시 Network 모듈 외 밖에서 사용하는거라면, public 이여야 되지 않을까요?
그떄 말씀하신 외부에서 사용하는 예시를 생각하셨다면요!

2024-07-05 06:53 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    func upload<T: Decodable>(endpoint: APIEndpoint, data: [UploadData]) -> Single<T> {
request와 마찬가지로 `public`이어야 하겠네요! [569407f](https://github.com/depromeet/WalWal-iOS/pull/1/commits/569407f64338503596f7d519a1c59fb9f118c051) 여기에서 수정 완료입니다

2024-07-05 06:54 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +final class NetworkReachability {
[569407f](https://github.com/depromeet/WalWal-iOS/pull/1/commits/569407f64338503596f7d519a1c59fb9f118c051) 
여기도 `pulbic` 으로 수정했습니다! 꼼꼼하게 봐주셔서 감사해요 ~!

2024-07-05 06:54 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/APIEndpointImpl.swift
> +
아래 NetworkServiceImpl와 같이 [dbfe0ee](https://github.com/depromeet/WalWal-iOS/pull/1/commits/dbfe0ee0e7c2e3b7ac4ac4818f01d2f4f8bc3125) 여기에서 공백 제거 했습니다 ~ 감사합니다!

2024-07-05 07:31 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/APIEndpointImpl.swift
> +            urlRequest.url = try configureQueryParams(url: url.appendingPathComponent(path), query: query)
`asURLRequest()` 내부에서 생성한 url을 사용하기 위함이었습니다! 그런데 다시 보니, url 생성이 조금 반복되는 것 같아서 아래와 같이 url 생성 함수를 만들어보았는데 이 방법은 어떤가요 ?!
https://github.com/depromeet/WalWal-iOS/pull/1/commits/a12dce11b8dc425c6f4564b15c736874cecc1d4c

2024-07-05 07:41 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +        return prettyPrintedString as String
옵셔널 String으로 해두었던 이유는 옵셔널 언래핑을 할 때 nil을 반환할 수 있어서 해두었습니다! 타입캐스팅도 String?으로 하는 게 안전할까요?!

2024-07-05 07:51 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/APIEndpointImpl.swift
> +            urlRequest.url = try configureQueryParams(url: url.appendingPathComponent(path), query: query)
@Zoe0929 
커밋 내용 확인했습니다!
관련해서 추가의견 코멘트 남겼어요~!

2024-07-06 04:20 UTC, ji-yeon224 requested changes

2024-07-06 04:20 UTC, ji-yeon224 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    func isReachable() -> Bool {
개인적인 의견인데 네트워크 연결 확인하는 기능을 Rx 사용해서 연결 상태값을 이벤트 방출하는 형식으로 만드는건 어떨까요? 전반적으로 Rx를 사용하기로 했기 때문에 네트워크 통신 전에 확인하거나 네트워크 상태를 감지해서 UI를 변경해야 할 경우 좀 더 편리하게 처리할 수 있지 않을까 생각되어 의견 드립니다~!😊

2024-07-06 07:19 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    func isReachable() -> Bool {
[29b2b31](https://github.com/depromeet/WalWal-iOS/pull/1/commits/29b2b31c570485191b8e31a785fb5c84fa89b0a2) 여기서 적용했습니다! 감사합니다!

2024-07-07 23:12 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +        return prettyPrintedString as String
@Zoe0929 말씀해주신거처럼 옵셔널 언래핑 할때 nil을 반환할 수 있어서 해두었다면 타입캐스팅도 그렇게 되야하지않을까요? 그 의도로 만드신거라면 as String? 이 맞는거같아요!

2024-07-08 08:24 UTC, usa4060 requested changes

2024-07-08 08:24 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    statusPublish
statusPublish에 대한 접근을 또다른 computed property로 하는 이유가 있나요??

2024-07-08 08:24 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    .catchError { error in
catchError가 depreceted되고 catch로 바뀐것으로 알고있는데, 어찌 반대로 돌아간것이죠,,,?!

2024-07-08 08:24 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +      return self.decode(T.self, from: try JSONSerialization.data(withJSONObject: data))
`requestJSON`에서 return되는 `data`를 바로 from 파라미터에 넣는것과 차이가 있나요??

2024-07-08 14:04 UTC, kimkyunghun3 approved these changes
긴 리뷰 고생했슴다!

2024-07-08 16:39 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    .catchError { error in
버전 오류로 확인했습니다 감사합니다! 수정했어요!

2024-07-08 16:40 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +      return self.decode(T.self, from: try JSONSerialization.data(withJSONObject: data))
data가 Any 타입이라서 타입 캐스팅 실패하면 빈 값이 들어가더라구요 ! 그냥 Any로 받는 게 타입 캐스팅 에러가 적을 것 같아서 수정 했습니다.

2024-07-08 16:49 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +    statusPublish
크게 두가지 이유가 있을 것 같은데요!
1. 연산 프로퍼티로 statusPublish를 선언하면서 외부의 직접 접근하는 것을 방지하기 위해 사용했습니다
2. `.debug()`를 호출하여, 네트워크 상태 변화에 대한 로그를 출력하기 위해 사용했습니다

2024-07-09 01:25 UTC, ji-yeon224 approved these changes
고생하셨습니다~

2024-07-09 04:38 UTC, usa4060 approved these changes
고생하셨습니다~

2024-07-09 05:41 UTC, merged