Refactor/network module
depromeet/WalWal-iOS pull request #10
Opened 2024-07-11 02:34 UTC by usa4060

## 📌 개요
Feature모듈 분리에 따라 Dependency관계를 좀 더 고려한 Network Module 코드 개선
## ✍️ 변경사항
- 기능적인 측면 보다는, 의존성 분리에 따른 타입 캐스팅 관점에서의 코드 수정이 주로 있습니다.
- 또한, 실제 각 레이어에서의 사용처에서 어떤식으로 적용할 지에 대해 고민하여 예제코드를 작성하였습니다.
-> 최대한 단방향 의존성을 추구하면서, 레이어의 독립성을 보장하기위해 노력함...
## 📷 스크린샷
X
## 🛠️ **Technical Concerns(기술적 고민)**
X

2024-07-11 06:16 UTC, kimkyunghun3 requested changes
고생했습니다 자잘한 수정이랑 대응만 해주시면될거같아요~!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/DTO/AuthDTO.swift
> +  func toModel() -> AuthModel {
예시이긴하지만, 내부 로직없이 바로 return 이라면 연산프로퍼티는 어떤가요~?

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +enum AuthEndpoint<EP>: APIEndpoint where EP: Decodable {
EP 의미가 뭐에요?!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +  // MARK: - Properties
레퍼지토리에서 MARK가 필요한 사이즈가 아닐 수 있는데 요 부분 쓰실려면 같이 이야기해보면 좋을거같아요
+ MARK 컨벤션은 위아래 띄워쓰기라 같은 파일내 확인해주세요~!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +  // - Interface에 정의된 함수를 구현해주세요.
/// 주석방식으로!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthDomain/Implement/SignInUseCaseImpl.swift
> +
여기 컨벤션 띄어쓰기 하기루했었나요 혹시?? 써드파티랑 내부랑만 구분하는거같은데 확인해주세요~!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +public class AuthDataRepositoryImpl: AuthDataRepository {
상속여부?! 확인해주세요

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Interface/Repository/AuthDataRepository.swift
> +import RxSwift
띄어쓰기

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +    networkService: NetworkServiceProtocol
다른곳은 줄바꿈안한거같은데 이곳은 혹시 길어서 줄바꿈한건가요?

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  private func bindEvent() {
기억이 안나는데 bindEvent도 하기루했었나요.,.? 어떤거를 넣나요 요거는?

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkReachability.swift
> +import UIKit
이거 2개인데 하나로 합쳐주세요

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkReachability.swift
> +  public func isReachable() -> Bool {
머를 수정한지 정확히 몰라서 리뷰를 달자면.. 이거는 바로 반환이라 연산프로퍼티면 좋을거같아요!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +  private func convertToResponse<WAL: Decodable>(
WAL, EP 등 여러곳에서 제네릭 용어를 다양하게 쓰는 것도 좋은데
제 생각에서는 모두가 이해하고 맞춘게 아니라면 공용어로 쓰면 좋을거같아요 T, U, V 등
어떤 의미인지 파악하는것보다 공용어로 쓰면 더 이해가 쉬워보입니다!!

2024-07-11 06:16 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Interface/NetworkService.swift
> +//  func upload<T: Decodable>(endpoint: APIEndpoint, data: [UploadData]) -> Single<T>
이거는 주석이 된건 안쓰는걸까요?

2024-07-11 06:17 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +enum AuthEndpoint<EP>: APIEndpoint where EP: Decodable {
요건 아래에 이야기함!

2024-07-11 06:30 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/DTO/AuthDTO.swift
> +  func toModel() -> AuthModel {
아 이 코드는 안쓰는 더미파일이에요..! 지우는걸 깜빡 ㅎ.,,
DTO로 사용하는건 Interface쪽 봐주시면 됩니다!

2024-07-11 06:35 UTC, ji-yeon224 requested changes

2024-07-11 06:35 UTC, ji-yeon224 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +  private func convertToResponse<WAL: Decodable>(
저도 동의합니다!

2024-07-11 06:35 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  override func viewDidLoad() {
저번에 한번 이야기 하긴 했는데 `viewDidLoad()`랑 `bind()` public으로 변경 부탁드릴게용~

2024-07-11 06:38 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +enum AuthEndpoint<EP>: APIEndpoint where EP: Decodable {
연관타입의 Response를 대응하기위한 별명으로 EP라고 우선 샘플명을 지어놨는데,
말 해주신대로 토요일에 제네릭 네이밍 관련 이야기도 해보면 좋을 것 같네요!!

결론적으로는 BaseResponse가 제네릭타입(Decodable한) DTO의 타입을 받아오기 때문에, 타고타고 올라와서 쓰게 되었습니다 ㅎ,,

2024-07-11 06:39 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +  // MARK: - Properties
넵 컨벤션 확인 했습니다~!
MARK의 범위에 대한 논의도 좋아요~

2024-07-11 06:40 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Implement/SignInUseCaseImpl.swift
> +
아 인터페이스는 프레임워크라 붙이는게 맞을 것 같네요

2024-07-11 06:41 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +    networkService: NetworkServiceProtocol
네 느낌적인느낌으로 길어서 줄바꿈 하긴 했는데,,,
뭔가 확실하게 정하는게 나을까요?
@kimkyunghun3

2024-07-11 06:43 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  private func bindEvent() {
뭔가 이 부분은 처음 템플릿 만들 때 구성한 부분이라,,,,저도 가물가물 하네요
@ji-yeon224 우리 `bindEvent()` 따로 만들어놓은 이유가 따로 있었나???

2024-07-11 06:44 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkReachability.swift
> +  public func isReachable() -> Bool {
@Zoe0929 
지희가 답변 달아주면 좋을 것 같네여~

2024-07-11 06:45 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +  private func convertToResponse<WAL: Decodable>(
넵 동의합니다! 사실상 의미 자체는 모두 DTO를 의미하는 제네릭 용어라서, 
토요일에 같이 이야기 나누고 공용어로 맞추면 좋을 것 같네요

2024-07-11 06:45 UTC, usa4060 commented on WalWal/WalWalNetwork/Interface/NetworkService.swift
> +//  func upload<T: Decodable>(endpoint: APIEndpoint, data: [UploadData]) -> Single<T>
넵 지워두겠습니다!

2024-07-11 06:46 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  override func viewDidLoad() {
넵 템플릿 수정해서 한번에 다시 올릴게용

2024-07-11 06:47 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +public class AuthDataRepositoryImpl: AuthDataRepository {
@kimkyunghun3 
상속 여부라함은 어떤 내용일까요??

2024-07-11 06:57 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  private func bindEvent() {
스읍 이게 제가 의견을 냈었던걸까요..? 제가 리액터킷 쓸 때 리액터 관련한 것 외에 바인딩하는 경우를 bindEvent()에 작성하긴 합니다..! 굳이 Reactor를 거치치 않아도 되고 단순하게 UI 관련한 이벤트를 처리하는 경우에 사용할 수 있을 것 같아요~
어떤 경우에는 필요하기도 하고 쓰지 않아도 되는 경우가 있기도 해서 논의해보면 좋을 것 같아요!

2024-07-11 07:10 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  private func bindEvent() {
이것도 토욜에 같이 논의 하는걸로~

2024-07-11 22:28 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkReachability.swift
> +  public func isReachable() -> Bool {
@kimkyunghun3 @usa4060  오, 연산 프로퍼티가 더 좋을 것 같네요! 이건 머지 이후에 따로 수정하는 게 나을까요?

2024-07-11 22:43 UTC, Zoe0929 approved these changes
예시 코드까지 꼼꼼하게 작성해주셔서 참고하기 좋을 것 같아요! 감사합니다 😊

2024-07-11 22:43 UTC, Zoe0929 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +      ]
구현 예시를 보며 생각났는데, 이런 헤더는 아마 모두 사용될 것 같은데 default 헤더 타입을 만들어볼까요?!

2024-07-11 22:43 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
>    }
로그 더 깔끔하게 볼 수 있도록 수정해주셨군요! 감사합니다!

2024-07-12 02:24 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +      ]
content-type이 application/json 이외의 다른 값이 들어갈 수도 있어서 (dataForm(?)과 같은,,) 조금 더 지켜봐도 좋을 것 같아요~

2024-07-12 03:12 UTC, kimkyunghun3 commented on WalWal/WalWalNetwork/Implement/NetworkReachability.swift
> +  public func isReachable() -> Bool {
@Zoe0929 넹 담에 해욤

2024-07-12 03:12 UTC, kimkyunghun3 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +public class AuthDataRepositoryImpl: AuthDataRepository {
@usa4060 맞아여 상속하는 친구가 아니면 final 이 있어야되지않나 해서요~

2024-07-12 03:24 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +enum AuthEndpoint<EP>: APIEndpoint where EP: Decodable {
https://github.com/depromeet/WalWal-iOS/pull/10/commits/8aab0df588d3703b4fdf69bc556e681263575009
해당 커밋 참고 해주세요~

2024-07-12 03:24 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +  // MARK: - Properties
https://github.com/depromeet/WalWal-iOS/pull/10/commits/8ac79b48f55bcc6d6719d30dd5b17e7cb3b8f6fc

2024-07-12 03:24 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +  // - Interface에 정의된 함수를 구현해주세요.
https://github.com/depromeet/WalWal-iOS/pull/10/commits/253284052558d92eb24edc2788fb17694ed2d2e2

2024-07-12 03:25 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Implement/SignInUseCaseImpl.swift
> +
https://github.com/depromeet/WalWal-iOS/pull/10/commits/b9863f235d61878ba83a73e2c2fa281041e87062

2024-07-12 03:25 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repositories/AuthDataRepositoryImpl.swift
> +public class AuthDataRepositoryImpl: AuthDataRepository {
[final 키워드 수정](https://github.com/depromeet/WalWal-iOS/pull/10/commits/66f604cfc1d15cecdd2012222910f6a29b7f9b0c)

2024-07-12 03:25 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Interface/Repository/AuthDataRepository.swift
> +import RxSwift
[띄어쓰기 관련 컨벤션 수정](https://github.com/depromeet/WalWal-iOS/pull/10/commits/b9863f235d61878ba83a73e2c2fa281041e87062)

2024-07-12 03:26 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/DTO/AuthDTO.swift
> +  func toModel() -> AuthModel {
[더미파일 제거](https://github.com/depromeet/WalWal-iOS/pull/10/commits/1e215c282bdd09fa446cc226e87cbf929aace1ba)

2024-07-12 03:26 UTC, usa4060 commented on WalWal/WalWalNetwork/Implement/NetworkServiceImpl.swift
> +  private func convertToResponse<WAL: Decodable>(
[제네릭 타입명 공용어 관련 수정](https://github.com/depromeet/WalWal-iOS/pull/10/commits/8aab0df588d3703b4fdf69bc556e681263575009)

2024-07-12 03:28 UTC, usa4060 commented on WalWal/WalWalNetwork/Interface/NetworkService.swift
> +//  func upload<T: Decodable>(endpoint: APIEndpoint, data: [UploadData]) -> Single<T>
[제네릭 타입명 공용어 관련 수정](https://github.com/depromeet/WalWal-iOS/pull/10/commits/8aab0df588d3703b4fdf69bc556e681263575009)
해당 커밋에서 같이 작업했습니다~!

2024-07-12 03:30 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/View/AuthView.swift
> +  override func viewDidLoad() {
[infra: LocalStorage 모듈 생성](https://github.com/depromeet/WalWal-iOS/commit/2c7c2ddf3b22590384869d482b52c17905e6c144)
해당 커밋에서 작업 해두었습니다~

2024-07-12 04:24 UTC, kimkyunghun3 approved these changes
고생했어요 확인했습니다~

2024-07-12 06:10 UTC, ji-yeon224 approved these changes
고생하셨습니다~

2024-07-13 09:14 UTC, merged