로그아웃 및 회원 탈퇴 구현
depromeet/WalWal-iOS pull request #127
Opened 2024-08-17 05:56 UTC by ji-yeon224

## 📌 개요
로그아웃 및 회원 탈퇴를 구현하였습니다.

## ✍️ 변경사항
- 로그인 시 소셜로그인 타입을 UserDefaults에 저장하여 카카오 로그아웃 및 탈퇴 로직을 처리하였습니다.

## 📷 스크린샷

https://github.com/user-attachments/assets/d964e70f-c00c-4674-9875-bc85b09f0a75

로그아웃 -> 탈퇴 -> 회원가입 순 

## 🛠️ **Technical Concerns(기술적 고민)**

2024-08-17 06:08 UTC, usa4060 requested changes
- 카카오 로그인 관련
- 컨벤션 확인 부탁 드립니당~

2024-08-17 06:08 UTC, usa4060 commented on WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
>    public var myPageDependencyFactory: MyPageDependencyFactory
생각해보니까 이거 접근제한자 전부 `private`으로 돌려야겠네,,, 다른 `coordinatorImp`들도

2024-08-17 06:08 UTC, usa4060 commented on WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
>    public var myPageDependencyFactory: MyPageDependencyFactory
-> `private let `

2024-08-17 06:08 UTC, usa4060 commented on WalWal/DependencyFactory/WalWalTabBar/WalWalTabBarDependencyFactory/Project.swift
>      /// .DependencyFactory.Notification.Interface,
주석 제거

2024-08-17 07:37 UTC, Zoe0929 approved these changes
고생하셨습니다~

2024-08-17 13:32 UTC, ji-yeon224 commented on WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
>    public var myPageDependencyFactory: MyPageDependencyFactory
https://github.com/depromeet/WalWal-iOS/pull/127/commits/022b37710a18db9ffb20c8cf12cc32085f7f7996
요거 일단 해당 Pr에서 수정 작업 있었던 app, auth, mypage coordinator만 `private let`로 바꿔뒀습니다!

2024-08-18 07:13 UTC, usa4060 approved these changes
고생했습니답

2024-08-18 12:22 UTC, merged