미션 API 연결
depromeet/WalWal-iOS pull request #129
Opened 2024-08-18 19:22 UTC by Zoe0929

## 📌 개요
미션 뷰에 필요한 API 연결 완료 했습니다.

## ✍️ 변경사항
1. WalWalButton_icon
- titleLabel의 너비에 따른 레이아웃 이슈가 있었습니다. 
- `.markDirty`를 추가하여 텍스트가 달라지면, 너비가 변하게 만들었습니다.
2. 타이머 구현 
- 미션 상태에 따라 미션 시작을 누른 경우에는 Timer가 표출되게 변경했습니다 

## 📷 스크린샷
![Simulator Screen Recording - iPhone 13 mini - 2024-08-19 at 03 15 50](https://github.com/user-attachments/assets/5515e31d-b926-4f9d-8d3a-944fb745fae8)

## 🛠️ **Technical Concerns(기술적 고민)**
현재 데이터를 viewDidLoad일 때 호출합니다. 
때문에 데이터 로딩까지 약간 깜빡임이 있는데, 미션 상태와 미션 이미지를 캐싱하는 작업이 필요할 것 같습니다!

2024-08-18 22:56 UTC, usa4060 requested changes
고생하셨습니다~ 코멘트 확인 부탁드려유
근데 나 이렇게 BubbleView쪽 Text가 짤리는데 나만 그러니?
![IMG_5227](https://github.com/user-attachments/assets/7c2a22e9-1aa7-4d88-b594-840a7d62dc4a)

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Coordinators/Mission/MissionCoordinator/Implement/MissionCoordinatorImp.swift
> +import MissionDomain
[임포트 컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#4-%EC%9E%84%ED%8F%AC%ED%8A%B8)

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionDomain/Implement/TodayMissionUseCaseImp.swift
>        }
이렇게 UseCaseImp에서 직접적으로 DTO를 노출하는 것 보다,
Model의 initalizer에 파라미터로 dto를 넘겨주고, 프로퍼티의 값을 할당해주는게 좋을 것 같아요
`.map { MissionModel(dto: $0) }` 
이런 식으로!

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionDomain/Interface/UseCase/TodayMissionUseCase.swift
>    func excute() -> Single<MissionModel>
이것도 저번에 말 했던 것 처럼, 제가 템플릿 만들 때 오타난 부분이라,,,,
나머지 `excute`들도 전부 `execute`로 수정 부탁드려욥

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +  public let todayMissionUseCase: any TodayMissionUseCase
오잉? 여기 UseCase들은 왜 `any` 타입이 붙어있는걸까욥??
따로 특정 protocol을 채택하지 않는 이상, `any`는 때도 괜찮을 것 같아요

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +              return self.checkMissionStatus(id: mission.id).startWith(mutation)
closure내부라 self에 약한참조 걸어야 할 것 같아요

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +          .flatMap { mutation -> Observable<Mutation> in
뭔가 이 flatMap되는 로직도 함수로 따로 만들어서 사용하는게 미관상(?) 깔끔해 보일 것 같긴 하네여

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  private func calculateTimeRemainingUntilMidnight() -> String {
이 로직은 View에서 분리하는게 좋을 것 같아요

2024-08-18 22:56 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  private func startCountdownTimer() {
흠,,, 이 친구를 View에서 가지고 있는 방법 밖에는 없을까요??

2024-08-18 22:59 UTC, usa4060 commented
@Zoe0929 
추가적으로, 결국 스플래시 단계에서 초기 데이터로 한번 호출하는 과정이 필요해보이기는 하네요,,,

2024-08-19 00:19 UTC, ji-yeon224 approved these changes
고생했어용~

2024-08-19 00:24 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +  public let todayMissionUseCase: any TodayMissionUseCase
[d09e6e3](https://github.com/depromeet/WalWal-iOS/pull/129/commits/d09e6e363c16dbab465c06dede2e12445dc0d22d) 요거 수정 완료입니다~!

2024-08-19 00:24 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionDomain/Interface/UseCase/TodayMissionUseCase.swift
>    func excute() -> Single<MissionModel>
[9811d3b](https://github.com/depromeet/WalWal-iOS/pull/129/commits/9811d3bf35dad88d36f9392fbd57bb22b38203b0) 수정 완료했습니다!
피드에도 똑같은 실수 있는데, 피드 데이터 연결하고 있는 브랜치에서 이어서 작업하겠습니다~

2024-08-19 00:25 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +          .flatMap { mutation -> Observable<Mutation> in
[76f57bd](https://github.com/depromeet/WalWal-iOS/pull/129/commits/76f57bd691515a3a38d46285e27abc1983e53c62) 이렇게 묶어봤습니다~ 감사합니당!

2024-08-19 00:26 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionDomain/Implement/TodayMissionUseCaseImp.swift
>        }
[c8df0fe](https://github.com/depromeet/WalWal-iOS/pull/129/commits/c8df0fe72fdc47396329d1c8d96f657abf7836ac) 얘만 다르게 만들어놨었네요~ DTO 인자로 넣어주는 걸로 변경 완료입니다!

2024-08-19 00:44 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  private func calculateTimeRemainingUntilMidnight() -> String {
[f82b446](https://github.com/depromeet/WalWal-iOS/pull/129/commits/f82b446f59b7817c1779a3b1b741769a1354efd9) 뷰로 이동하면서, ButtonText를 미션 상태에 따라 다르게 전달하는 걸로 로직을 살짝 바꿔보았습니다! 확인해주시면 감사하겠습니다~~

2024-08-19 10:36 UTC, usa4060 approved these changes
고생했습니다~

2024-08-20 03:28 UTC, merged