피드 로딩 Lottie 추가 및 피드 데이터 연결
depromeet/WalWal-iOS pull request #137
Opened 2024-08-19 15:25 UTC by Zoe0929

## 📌 개요
피드 로딩 Lottie 및 피드 데이터 연결했습니다!

## ✍️ 변경사항
Global State에 데이터 저장하는 것은 임시 구현입니다! 코드 리뷰 후 수정하겠습니다.
로티 이미지 레이아웃도 현재 임시로 고정 시켜둔 상태 입니다. 

## 📷 스크린샷
![Simulator Screen Recording - iPhone 13 mini - 2024-08-20 at 00 22 43](https://github.com/user-attachments/assets/88422ccb-bb33-4538-b131-2c583471480f)

## 🛠️ **Technical Concerns(기술적 고민)**

2024-08-19 16:40 UTC, usa4060 requested changes
고생하셨습니다

2024-08-19 16:40 UTC, usa4060 commented on WalWal/Features/Feed/FeedData/Interface/DTO/FeedDTO.swift
> +  public  let missionTitle: String
인덴트

2024-08-19 19:23 UTC, ji-yeon224 approved these changes
고생했어용~!

2024-08-22 01:16 UTC, usa4060 approved these changes
고생했슴당

2024-08-22 01:17 UTC, merged