MissionView 권한 검사 로직 추가
depromeet/WalWal-iOS pull request #139
Opened 2024-08-19 18:40 UTC by Zoe0929

## 📌 개요
#138 
재설치 시 온보딩을 거치지 않아 권한 요청을 하지 않는 오류를 해결했습니다. 

## ✍️ 변경사항
1. MissionView 진입 시 Noitification 권한 검사 및 요청
2. `미션 시작하기` 버튼 클릭 시 Camera 권한 검사 및 요청
3. 프로필 이미지 변경 시 Photo 권한 검사 및 요청

## 📷 스크린샷
|  미션 시작 시 카메라 권한   |  로그인 이후 알림 권한 | 프로필 변경 시 갤러리 권한|
|----------------------------------------------------------|----------------------------------------------------------|----------------------------------------------------------|
| <img src="https://github.com/user-attachments/assets/1bdaa154-ca2f-4aa5-91c1-81da589a3b09" width="300"/> | <img src="https://github.com/user-attachments/assets/c6283842-537a-4e23-a6fc-cb4e92660ea6" width="300"/> | <img src="https://github.com/user-attachments/assets/60bace73-da7e-4d76-b642-187a3b924ea6" width="300"/> |

## 🛠️ **Technical Concerns(기술적 고민)**

2024-08-19 19:29 UTC, ji-yeon224 reviewed
고생해써요! 코멘트 확인해주세용

2024-08-19 19:29 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor.action
요거 뷰 진입하자마자 action보내고 싶은거면 `transform(action: )`으로 처리할 수 있을거에용
MyPageReactorImp 참고해보면 좋을 것 같아요
[MyPageReactorImp.swift](https://github.com/depromeet/WalWal-iOS/blob/develop/WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/MyPageReactorImp.swift)

2024-08-19 19:29 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileEditViewImp.swift
> +        owner.reactor?.action
오잉 이거 flatMap으로 확인하고 권한 확인되면 PHPickerView 열어야하지 않나요??? 거절 해도 열릴 것 같은뎅..

2024-08-19 20:58 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor.action
[46ae6ed](https://github.com/depromeet/WalWal-iOS/pull/139/commits/46ae6ed169e3c09413193cb8921b17528583d4d2) 여기서 반영했습니다! 감사합니다!!

2024-08-20 00:18 UTC, usa4060 requested changes
@Zoe0929 @ji-yeon224 
아 그리고 추가적으로 든 생각인데, UI의 통일성을 위해서는
온보딩에 있는 `PermissionView()`이 친구를 활용해보는건 어떨까 싶긴 합니다
[ 앱 최초 설치 + 이미 계정이 있는 경우 ]의 케이스에서, 처음 진입 화면인 미션에서 
한번에 3개의 권한을 받으면 어떨까 싶네요??

물론 알림을 제외한 카메라 & 사진의 경우는 현재처럼 각 프로세스에서도 존재 해야하구요!
- 그렇게 되었을 때, 거절을 한 경우에만 재차 권한에 대한 요청을 하기 때문에 유저경험이 더 괜찮을 것 같다는 생각이에요
- 또한 알림허용은, 설정에 따로 탭이 존재해야하지 않을까 하는 생각입니다

2024-08-20 00:18 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    missionStartButton.rx.tapped
좀 더 가독성 좋은 코드를 위해서, 
```swift
missionStartButton.rx.tapped
      .map{ Reactor.Action.startMission }
      .bind(to: reactor.action)
      .disposed(by: disposeBag)
```
이렇게 작성 해보는건 어떨까용

2024-08-20 00:18 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    missionStartButton.rx.tapped
아 그리고 뭔가 버튼이 잘 안눌리는 것 같길래 확인 해보니까
위에 BubbleView가 버튼 상단에 살짝 걸쳐있어서, 해당 영역 버튼의 인터렉션을 막고 있는 것 같아용
![스크린샷 2024-08-20 오전 8 40 00](https://github.com/user-attachments/assets/4e349bc4-b1b1-43af-b1d7-b2a660a790a2)

`point(inside:with:)` 이 메서드를 한번 찾아보세용
(버블뷰의 터치 이벤트를 통과시키는게 힌트)

2024-08-20 00:18 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +                // 권한 없음 -> 토스트 메시지로 권한 요청?
해당 방식으로 진행해야할 것 같슴다~
커스텀 얼럿으로 할 지, 기본 얼럿으로 할 지는 디쟌팀에 물어봐야할 듯

2024-08-20 00:18 UTC, usa4060 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileEditViewImp.swift
아 그리고 방금 확인했는데,
`View`에 있는 `bindEvent()` 내부에서
`navigationBarView.rightItems?.first?.rx.tapped`로직에서 바로 화면전환이 발생하고 있네욤,,, ([137번째 줄](https://github.com/depromeet/WalWal-iOS/blob/46ae6ed169e3c09413193cb8921b17528583d4d2/WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileEditViewImp.swift#L140))
화면전환의 `reactor`내부에 있는 `coordinator`에게 책임을 넘겨야함미다
따라서, `navigationBarView.rightItems?.first?.rx.tapped`에서 `action`을 넘겨주고
해당 액션을 통해서 `reactor`의 `mutate`를 통해 `coordinator.popToRootViewController`이런 식으로 다뤄줘야해요!!


### 화면전환은 항상 coordinator에게 책임을 부여해야합니다! (강조x100)
(ps. 코디네이터 엄청엄청 열심히 만들었는데,,, 안써주면 매우 슬픔,,,)

2024-08-20 00:18 UTC, usa4060 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileEditViewImp.swift
> +        owner.reactor?.action
실제로 테스트 해보니까, 권한이 없는데도 바로 picker가 열리네영
(근데 권한이 없는데 열리는 것도 신기하네,,,)

2024-08-20 01:43 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +                // 권한 없음 -> 토스트 메시지로 권한 요청?
얼럿 쓰는거면 회원탈퇴에 디자인되어있는 얼럿쓰면 될거같기두,, 아직 안만들엇서요ㅠㅠ

2024-08-20 03:26 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileEditViewImp.swift
에 이거 왜 그랬지!! 확인 감사합니다!! 진짜진짜 실수임!! 코디네이터 너무 유용함!!

2024-08-20 04:37 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    missionStartButton.rx.tapped
[9cad392](https://github.com/depromeet/WalWal-iOS/pull/139/commits/9cad392e0398911da13495b51211933f7bb78856) 감사합니다~! 
rebase 이후에 버블뷰 위치가 겹치는 영역이 적어져서 제대로된 상황 연출이 어려워서 현 상황에서 또 발생하는지 확인 부탁드립니다!(저는 버튼 잘 눌렸습니당)

2024-08-20 08:36 UTC, ji-yeon224 approved these changes

2024-08-20 08:36 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileEditReactorImp.swift
> +    case let .setPhotoPermission(isAllow: isAllow):
이슈는 아니지만 isAllow: 요거 없애두 되지 않나영?-?

2024-08-20 15:42 UTC, usa4060 approved these changes
고생하셨습니다

2024-08-20 15:47 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileEditReactorImp.swift
> +    case let .setPhotoPermission(isAllow: isAllow):
음! 어차피 매번 체크하니까 괜찮겠네요~

2024-08-20 15:52 UTC, merged