알림 탭 구현
depromeet/WalWal-iOS pull request #249
Opened 2024-09-05 08:00 UTC by ji-yeon224

## 📌 개요
- issue: #236 
알림 탭 구현 및 화면 이동

## ✍️ 변경사항
- 알림 리스트를 보여주고, 아이템 선택 시 알맞는 화면으로 이동
- global state로 알림 리스트도 미리 불러오도록 구현

## 📷 스크린샷
### iPhone 12pro
https://github.com/user-attachments/assets/f8da7eff-a52b-4ee4-a46d-952e9d5dca55

### iPhone 8
https://github.com/user-attachments/assets/7c21a915-357f-40d9-86b5-5b3b5de128b0

## 🛠️ **Technical Concerns(기술적 고민)**
알림 탭 - 피드 탭 이동 시 recordId 값을 전달해야해서 GlobalState에 저장해서 탭 이동 후 GlobalState에 저장해둔 recordId로 접근하도록 했는데 이게 맞는 방법일까요?

2024-09-05 09:21 UTC, Zoe0929 approved these changes
고생하셨습니다! 🥺

2024-09-05 09:21 UTC, Zoe0929 commented on WalWal/WalWalNetwork/Sources/Foundation/NetworkServiceImp.swift
> +        dump(errorResponse)
요거 없어도 될 것 같아요!

2024-09-05 09:58 UTC, usa4060 requested changes
코멘트 확인 부탁드림다

2024-09-05 09:58 UTC, usa4060 commented on WalWal/DependencyFactory/Feed/FeedDependencyFactory/Implement/FeedDependencyFactoryImp.swift
> +  public func makeFeedViewController<T>(reactor: T) -> any FeedViewController where T : FeedReactor {
make -> inject

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Implement/FCMListUseCaseImp.swift
> +        self.saveFCMListGlobalStateUseCase.execute(fcmList: items, globalState: GlobalState.shared)
이거 `FCMListUseCaseImp`의 `execute`를 하는 곳에서, `flatMap`으로 `item`을 전달받아서
`saveFCMListGlobalStateUseCase`에서 별도로 처리하는게 좋을까??
아니면 지금 작성된 방식으로 하는게 좋을까??

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Implement/RemoveGlobalFCMListUseCaseImp.swift
> +      GlobalState.shared.fcmList.accept([])
문제가 되는 부분은 아니지만, 이렇게 변수에 직접 접근하는 방식 보다는
`GlobalState`에 `method`로 `fcmList`를 비워주는 동작을 정의해두고,
외부에서는 해당 함수를 호출하는 방식으로 작성하는게, 코드 확장성이 더 좋을 것 같다는 생각?

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Implement/SaveFeedRecordIDUseCaseImp.swift
> +    GlobalState.shared.moveToFeedRecord.accept(recordId)
이것도 사소하지만, `RemoveGlobalFCMListUseCaseImp`의 코멘트와 비슷한 맥락

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Implement/RemoveGlobalFCMListUseCaseImp.swift
> +      GlobalState.shared.fcmList.accept([])
근데 나도 사실 가끔 안지킬 때 있는 것 같은데 ㅋㅋ

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Interface/Model/FCMListModel.swift
> +  }
띄 어 쓰 기

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Interface/Model/FCMListModel.swift
> +  public init(dto: FCMItemDTO) {
뭔가 엄청 중복되는데, `convenience init` 쓸만한 케이스는 없을라나?
(단순 질문)

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
> +      return fetchFCMListUseCase.execute()
함수로 빼서 (return Mutation) 가독성을 높여보는게 어떤지

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
> +      return readFCMItem(item: item)
여기두

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
> +    GlobalState.shared.fcmList.accept([])
여기두 property 직접 접근

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
> +          return self.refreshFCMListData(cursor: nextCursor, limit: limit)
이거 페이징 기반으로, 스크롤 마다 호출하는게 아니라
한번에 다 부르는거로 결정??

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Views/Components/FCMCollectionViewCell.swift
> +
여기는 백그라운드 이슈 없나여??
모든 UI요소들 Container로 감싸지 않아도 괜찮으려낭

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
> +    } configureSupplementaryView: { datasource, collectionView, kind, indexPath in
현재 `ReactorKit`을 사용하고 있으니, `Model`자체를 직접 넘겨주기 보다는 `Model`에 `Reactor`를 채택하도록 해서, `Cell`의 `Reactor`로 할당 해주면 어떨까??

`RxDatasourece`와 `ReactorKit`을 사용하는 다양한 예제를 보니, 이렇게 사용하는 경우가 많더라구용

[참고자료1](https://ios-development.tistory.com/796)
[참고자료2](https://apple-apeach.tistory.com/36)

나도 `RxDatasource`를 사용해 본 적은 없어서, 정확하게는 모르는데
결국 현재 `configure()`함수에 넣는 파라미터가 `View`에 대한 `Model`이라면, 해당 모델을 `state`로 가지고 있는 `Reactor`를 정의해서 `Cell`의 `Reactor`로 전달하는게 더 깔끔해보이긴 한 느낌

2024-09-05 09:58 UTC, usa4060 commented on WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
> +      newState.scrollToFeedItem = id
더 좋은 변수명은 없을까,,,

2024-09-05 15:01 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMDomain/Implement/FCMListUseCaseImp.swift
> +        self.saveFCMListGlobalStateUseCase.execute(fcmList: items, globalState: GlobalState.shared)
reactor에서 `fcmListUseCase.execute`하고 다시 reactor에서 `saveFCMListGlobalStateUseCase.execute()` 실행 방식을 말하는거지?
사실 요건 귀찮아서 + 하나의 플로우라 내부에서 처리하고 싶어서 내부에서 처리하도록 하긴 했어. 사실 전자가 더 적절한거 같아 보이긴 한데 내부에서 한번에 처리하고 싶었달까..

2024-09-05 15:13 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMDomain/Interface/Model/FCMListModel.swift
> +  public init(dto: FCMItemDTO) {
요거 안그래도 뭔가 요상한 생김새라고 생각하긴 했는데,, 더 고민해 볼게유,, 좋은 방법 있으면 알려주십셔🥹

2024-09-05 15:33 UTC, ji-yeon224 commented on WalWal/Features/Feed/FeedPresenter/Implement/Reactors/FeedReactorImp.swift
> +      newState.scrollToFeedItem = id
ㅋㅋㅋㅋㅋ아 이거 나도 계속 고민하긴 했는데,, 더 고민 해보겠슴니다,,

2024-09-05 17:02 UTC, usa4060 commented on WalWal/Features/FCM/FCMDomain/Implement/FCMListUseCaseImp.swift
> +        self.saveFCMListGlobalStateUseCase.execute(fcmList: items, globalState: GlobalState.shared)
고민한 결과대로 해보시길~

2024-09-06 06:59 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMPresenter/Implement/Views/Components/FCMCollectionViewCell.swift
> +
넴 이슈 없슴다

2024-09-06 07:02 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMDomain/Implement/FCMListUseCaseImp.swift
> +        self.saveFCMListGlobalStateUseCase.execute(fcmList: items, globalState: GlobalState.shared)
https://github.com/depromeet/WalWal-iOS/pull/249/commits/ad35f05fb7714594b29208e97e6130345500f40a
코드 수정하다보니 `fcmListUseCase` 호출이 빈번하지 않아 그냥 GlobalState에 저장하는 usecase를 외부로 분리하였습니다!

2024-09-06 07:03 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMDomain/Implement/RemoveGlobalFCMListUseCaseImp.swift
> +      GlobalState.shared.fcmList.accept([])
https://github.com/depromeet/WalWal-iOS/pull/249/commits/97f6e05a1b2f1756f76d34047b8d8c928bc45a60
fcmList 비우는 메서드 생성하여 해당 메서드 호출해서 처리하도록 분리했습니다! 
다른 코멘트 부분도 적용 완료

2024-09-06 07:05 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMPresenter/Implement/Reactors/FCMReactorImp.swift
> +          return self.refreshFCMListData(cursor: nextCursor, limit: limit)
https://github.com/depromeet/WalWal-iOS/pull/249/commits/7135045d5c7861afdd996232accb8d82f8d5ba9a
생각해보니 페이징이 맞는거 같아서 스크롤 해서 호출하도록 변경했습니다. 
이미지 로드가 많이 필요하지 않아서 미션 홈 접근 시 미리 불러오지 않고, 알림 탭 들어갔을 때 불러오는 방식으로 변경했습니다!

2024-09-06 07:15 UTC, ji-yeon224 commented on WalWal/Features/FCM/FCMPresenter/Implement/Views/FCMViewImp.swift
> +    } configureSupplementaryView: { datasource, collectionView, kind, indexPath in
https://github.com/depromeet/WalWal-iOS/pull/249/commits/4470eff60ce38bcc31804ac6997e57ce63fa4ed9
해당 내용 적용하였습니다!

cell reactor를 인터페이스쪽에 구현해야하는 이슈가 있습니다..
구성 상 섹션의 아이템으로 reactor가 전달되어야 했고, 인터페이스 사용 시 아이템 타입이 명확하지 않아 문제가 발생하는 것 같습니당..
그래서 인터페이스 - 구현체 구조가 아닌 구현체만 사용하도록 구현하였습니다.
개선이 필요하다면 코멘트 남겨주세욥

2024-09-08 05:22 UTC, usa4060 approved these changes
늦어서 죄송함다 ㅎ,,

2024-09-09 01:39 UTC, merged