미션 완료 시 미션 탭 카드뷰 추가
depromeet/WalWal-iOS pull request #279
Opened 2024-10-03 17:23 UTC by Zoe0929

## 📌 개요
- issue: #266 

## ✍️ 변경사항
미션 완료 시 표시되는 카드 케라셀 뷰를 구현했습니다.
- 이미지 크기 이슈로 약간 확대하여 적용했습니다.

## 📷 스크린샷
https://github.com/user-attachments/assets/7ee90d38-00eb-4a30-b521-c93d8ae0f4d9

## 🛠️ **Technical Concerns(기술적 고민)**

2024-10-04 03:58 UTC, ji-yeon224 approved these changes
확인했습니다~ 고생해써요!

2024-10-04 04:06 UTC, usa4060 requested changes
고생하셨습니다~ 코멘트 확인 부탁드릴게여

2024-10-04 04:06 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
> +  func toggleContainers() {
현재 애니메이션 없이 단순히 View가 등장 및 제거 되는 것 같은데
디자인 의도대로라면 flip 애니메이션이 적용 되어야 할 것 같아요~
`UIView.transition `함수의 `.transitionFlipFromLeft`이 옵션을 한번 활용해보심이??

flip animation관련 자료는 아마 꽤 있을거에여

2024-10-04 04:06 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
> +          DispatchQueue.main.async {
drive로 구독하는거면 메인쓰레드를 지정 할 필요 없을 것 같아요

2024-10-04 04:06 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
> +          DispatchQueue.main.async {
drive내부 로직 -> `MainScheduler.ensureRunningOnMainThread(errorMessage: errorMessage)`

2024-10-04 08:32 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/MissionCompleteView.swift
> +          DispatchQueue.main.async {
오호 그렇군용 감사합니다!!

2024-10-04 10:11 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/Components/Cell/RecordCarouselCell.swift
> +  func toggleContainers() {
애니메이션 적용 완료입니다! 
https://github.com/user-attachments/assets/a57ec035-7417-43ec-a13e-09e300979edc

2024-10-05 12:53 UTC, usa4060 approved these changes
고생하셨습니다~

2024-10-05 14:06 UTC, merged