디자인시스템 ToastView 구현
depromeet/WalWal-iOS pull request #28
Opened 2024-07-19 04:12 UTC by kimkyunghun3

## 📌 개요
- 디자인 시스템 Toast 구현합니다.

## ✍️ 변경사항
- ToastView 구현(색상, margin, font 등은 제공되지 않아서 임의의 숫자로 적었습니다)

## 📷 스크린샷
![토스트뷰](https://github.com/user-attachments/assets/a529506d-1cc1-487b-8b46-585e8bf7b9a7)

## 🛠️ **Technical Concerns(기술적 고민)**
X

2024-07-19 04:52 UTC, usa4060 requested changes

2024-07-19 04:52 UTC, usa4060 commented on WalWal/DesignSystem/Sources/Toast.swift
> +
싱글톤으로 사용 할 때, 외부에서 인스턴스 생성되는 것을 막기 위해 private init을 정의하는게 좋을 것 같아요~
(모듈이 다르면 public으로 접근 해야해서, 지금 상태에서도 기본 internal init이라 생성이 안 되긴 하겠지만...!)

2024-07-19 04:52 UTC, usa4060 commented on WalWal/DesignSystem/Sources/Toast.swift
> +  private func createToastContainer() -> UIView {
Then으로 코드블럭을 작성하지 않은 이유가 있을까요??

2024-07-19 05:18 UTC, Zoe0929 approved these changes
고생하셨습니다!

2024-07-19 05:18 UTC, Zoe0929 commented on WalWal/DesignSystem/Sources/Toast.swift
> +}
정말정말 사소하지만! [빈줄 관련 컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#3-%EB%B9%88-%EC%A4%84)을 참고하면 파일 끝은 공백으로 끝나게 하자는 컨벤션이 있었습니다!

2024-07-19 05:25 UTC, ji-yeon224 approved these changes
확인했습니다! 고생하셨습니다~

2024-07-25 04:14 UTC, kimkyunghun3 commented on WalWal/DesignSystem/Sources/Toast.swift
> +
https://github.com/depromeet/WalWal-iOS/pull/28/commits/104935fa345dbd3e829075d369c6174b91f7d950
수정해써요!

2024-07-25 04:14 UTC, kimkyunghun3 commented on WalWal/DesignSystem/Sources/Toast.swift
> +  private func createToastContainer() -> UIView {
까먹었습니다..
https://github.com/depromeet/WalWal-iOS/pull/28/commits/104935fa345dbd3e829075d369c6174b91f7d950
수정했어요!

2024-07-25 04:14 UTC, kimkyunghun3 commented on WalWal/DesignSystem/Sources/Toast.swift
> +}
https://github.com/depromeet/WalWal-iOS/pull/28/commits/104935fa345dbd3e829075d369c6174b91f7d950
지금은 빈줄이 남아있죠....?!

2024-07-25 04:30 UTC, usa4060 approved these changes
고생하였습니다~👍🏻

2024-07-25 04:38 UTC, merged