로그인 화면 UI 구현
depromeet/WalWal-iOS pull request #29
Opened 2024-07-22 05:14 UTC by ji-yeon224

## 📌 개요
로그인 뷰 입니다.

## ✍️ 변경사항
로그인 모듈을 생성하고, UI 레이아웃을 구성하였습니다.

## 📷 스크린샷
<img src = "https://github.com/user-attachments/assets/e99e44cd-846a-4e3c-87c5-c13f190030ef" width="35%"/>

## 🛠️ **Technical Concerns(기술적 고민)**
레이아웃 구현 시 옵션마다 줄바꿈 하는것 가독성 괜찮은지?

2024-07-22 09:44 UTC, usa4060 requested changes
- 네트워크 테스트를 위해 Mock Response를 사용하는 것도 좋을 것 같습니다.
- Repository와 Usecase관련해서 남긴 글 한번 확인해보세요~
- #31 해당 PR이 올라가게 되면 각종 Dependency가 많이 간략화 될거에요. 참고 부탁드립니다.
- 뷰 관련해선, 모르는게 많아서,,ㅎ,,,;;

고생하셨습니다~

2024-07-22 09:44 UTC, usa4060 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthCoordinator(
함수 작성시도 마찬가지로 3개이상일 경우에 줄바꿈 하는게 좋을 것 같다는 의견
@ji-yeon224 @kimkyunghun3 @Zoe0929

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Coordinators/Auth/AuthCoordinator/Implement/AuthCoordinatorImpl.swift
> +  fileprivate func startAuth() {
Auth가 이미 Coordinator의 Stack상에 존재하는 상태인데, `startAuth()` 가 사용되는 이유가 뭔가요??
제가 처음 설계한 의도는, 현재 Coordinator에서 별개의 Flow를 실행하거나, 특정 View를 등장시키기 위해서 해당 extension을 만들었습니다!
혹시 제가 의도한 상황 이외에 다른 case가 존재한다고 판단하신거면 말씀해주세요~

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Coordinators/Auth/AuthCoordinator/Implement/AuthCoordinatorImpl.swift
> +  fileprivate func showAuth() {
위의 `startAuth()`쪽의 comment와 같은 맥락의 질문입니다!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Coordinators/Auth/AuthCoordinator/Project.swift
> +let project = Project.invertedDualTargetProject(
해당 코디네이터쪽 dependency의 경우, 제가 새로 올린 pr과 한번 비교 해보시면 좋을 것 같아요!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +  public func makeAuthData() -> AuthDataRepository {
혹시, API가 완성이 안되어서 소셜로그인 성공 이후 플로우 작업을 못하고 있다면
stubRepository를 만들어서 사용하는것도 좋아요~
(**stubRepository** -> 빠른 개발을 위해 API의 Mock Response를 모아두는 레포지토리)

2024-07-22 09:44 UTC, usa4060 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthUsecase() -> AuthUseCase
제 개인적인 생각으로는, `Usecase`는 각각의 비지니스 로직을 담당한다고 생각합니다.
현재 `AuthUsecase`내부에 선언되어있는 `AppleLogin`도 하나의 비지니스 로직이라고 볼 수 있겠죠.
그렇기 때문에, 저는 `AuthUsecase`가 아닌 `AppleLoginUsecase`라고 선언하고
내부에는 `excute()` 함수 하나만을 선언하는 구조를 선호합니다.
또한 이렇게 구현을 하게 되면, reactor에서 usecase를 다루게 될 때도, 좀 더 명확하게 '내가 현재 사용하는 `usecase`가 어떤 비지니스 로직이구나'를 명시할 수 있게되는 장점도 있습니다.

반면의 Repository의 경우는 데이터 처리의 기능을 주로 하다보니, 해당 도메인(우리의 경우는 Endpoint로 지정)과 관련된 모든 데이터 처리 작업을 진행하기 때문에 포괄적으로 묶어서 AuthRepository라고 명명하구요.

정리하면 Repository는 데이터 접근 로직을 추상화하여 여러 Usecase에서 재사용할 수 있도록 하기 위해 포괄적기능 단위로 묶어서 명명하고, Usecase를 구체적으로 명명하는 이유는 각 Usecase가 수행하는 작업(비지니스 로직)을 명확하게 나타내고, 단일 책임 원칙을 준수하며, 해당 기능에 대한 독립적으로 테스트를 가능하게 하기 위함입니다.

관련해서 혹시 질문이나 궁금한 점 있으면 질문 해주셔도 됩니다~

2024-07-22 09:44 UTC, usa4060 commented on WalWal/DependencyFactory/Project.swift
>    ]
해당 파일도, 제가 #31 PR로 올린 내용에서 수정된 부분이 있습니다~!
비교 확인 부탁드려용

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +    return URL(string: "")!
해당 URL에 들어가는 string의 경우도 config로 따로 관리하게 될거에요~!
방식은 저번에 오프라인으로 만났을 때 이야기 했던 방식대로~!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +      return "/auth/social-login/apple"
생각보다 path가 긴 것 같은데, `/auth`까지가 모두 공통된 경로라면 baseURL에 `"" + "/auth"`까지 추가하는 것도 좋을지도

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repository/AuthDataRepositoryImpl.swift
> +public final class AuthDataRepositoryImpl: AuthDataRepository {
이거 `impl` -> `imp`로 수정해주세요!
현재 템플릿은 아마 모두 imp로 되어있을거에요 (나머지 파일들도 확인 부탁합니다)

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Repository/AuthDataRepositoryImpl.swift
> +public final class AuthDataRepositoryImpl: AuthDataRepository {
아 추가적으로, layer명칭은 제거해도 좋을 것 같아요.
`AuthDataRepository` -> `AuthRepository`
다른 분들 의견은? @ji-yeon224 @Zoe0929 @kimkyunghun3

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Project.swift
> +  ]
해당 Project파일도 #31 PR에서 Dependency관련 수정 사항이 있습니다!
확인 부탁드려요~!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Implement/AuthUseCaseImpl.swift
> +public final class AuthUseCaseImpl: AuthUseCase {
명칭과 파일이름 마찬가지로 `impl` -> `imp`로!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Implement/AuthUseCaseImpl.swift
> +  public func appleLogin(authCode: String) -> Single<AuthToken> {
관련해서 `DependencyFactory` 코멘트에 의견 남겼습니다~

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Project.swift
> +  ]
마찬가지로 #31 관련해서 Dependency가 수정된 부분 있습니다~!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/DemoApp/Sources/AuthDemoAppDelegate.swift
> +import AuthPresenter
실제로 import가 필요한 것은 `DependencyFactoryImp` 밖에 없어요~!

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Interface/Reactors/AuthReactor.swift
> +  case appleLogin(authCode: String)
action에 대한 이름은 `tapped`와 같은 동적 명칭이 괜찮을 것 같다는 생각?

2024-07-22 09:44 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Project.swift
> +let project = Project.invertedPresenterWithDemoApp(
#31 참고해서, 필요없는 Dependency 확인 부탁드려욥

2024-07-22 14:38 UTC, Zoe0929 reviewed
고생 많으셨습니다! 단순 코멘트 몇 개 남겨 두었어요 :)
레이아웃 관련 컨벤션은 회의에서 맞춘대로 수정하시면 될 것 같아요!

2024-07-22 14:38 UTC, Zoe0929 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthCoordinator(
확인했습니당 좋아요!

2024-07-22 14:38 UTC, Zoe0929 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +    return URL(string: "")!
BaseURL이나 헤더같이 반복해서 사용되는 부분을 BaseAPIEndPoint로 만들어서 공유할지 고민이 되네요 🤔
@usa4060 @ji-yeon224 @kimkyunghun3  어떻게 생각하시나요!?

2024-07-22 14:38 UTC, Zoe0929 commented on WalWal/Features/Auth/AuthData/Implement/Repository/AuthDataRepositoryImpl.swift
> +public final class AuthDataRepositoryImpl: AuthDataRepository {
이름이 너무 길어진다면 생략해도 좋을 것 같네요!

2024-07-22 14:38 UTC, Zoe0929 commented on WalWal/Features/Auth/AuthData/Interface/Repository/AuthDataRepository.swift
> +  func appleLogin(token: String) -> Single<AuthTokenDTO>
서버 측에서 전달되는 기본 엔티티들을 정의한 BaseResponse를 사용하면 좋을 것 같아요!
``` swift
func appleLogin(token: String) -> Single<BaseResponse<AuthTokenDTO>>
```

2024-07-22 15:07 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthData/Implement/Repository/AuthDataRepositoryImpl.swift
> +public final class AuthDataRepositoryImpl: AuthDataRepository {
지금보니 굳이 layer명이 들어가지 않아도 될 것 같네요~ 없애는 것으로 가는게 좋겠슴다!

2024-07-22 15:17 UTC, ji-yeon224 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthUsecase() -> AuthUseCase
오 이해했습니다! 
그런데 애플로그인과 카카오로그인은 어찌보면 로그인이라는 같은 기능이라고 볼 수 있는데 소셜 타입이라는 작은 단위로 나누는건가요? 
만약 어떤 뷰 내에서 다양한 기능들이 존재한다면 usecase가 너무 많이 생기는 것이 아닌가 하는 생각이 들었습니다!

2024-07-22 15:34 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthData/Interface/Repository/AuthDataRepository.swift
> +  func appleLogin(token: String) -> Single<AuthTokenDTO>
엇 근데 request 요청 후 data layer에서 받는 리턴값은 DTO 데이터 혹은 error 아닌가욤?? 리턴타입에 BaseResponse가 붙어야 하는 이유를 잘 모르겠습니다!

2024-07-22 15:49 UTC, ji-yeon224 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthCoordinator(
https://github.com/depromeet/WalWal-iOS/pull/29/commits/3bdca5c6533de88495fd81d01c404726ae2583df
해당 커밋에서 줄바꿈 수정했습니다!

2024-07-22 15:51 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthData/Implement/Repository/AuthDataRepositoryImpl.swift
> +public final class AuthDataRepositoryImpl: AuthDataRepository {
https://github.com/depromeet/WalWal-iOS/pull/29/commits/e7971cd6f2faf3cbffd15f30525f11b715644317
https://github.com/depromeet/WalWal-iOS/pull/29/commits/d7f632bdc62cfd25a1cbaa00b239ae0b15b91621

2024-07-22 15:54 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/Interface/Reactors/AuthReactor.swift
> +  case appleLogin(authCode: String)
https://github.com/depromeet/WalWal-iOS/pull/29/commits/4c08b800da42d8e84f3ce9c979d2e6cab627af59
동의합니다! 버튼과 같은 이벤트의 경우는 action에 동작 명칭이 들어가는게 좋을 것 같아 수정했습니다~

2024-07-22 15:56 UTC, ji-yeon224 commented on WalWal/Coordinators/Auth/AuthCoordinator/Implement/AuthCoordinatorImpl.swift
> +  fileprivate func startAuth() {
https://github.com/depromeet/WalWal-iOS/pull/29/commits/e8bc546dbbe25bbfae95aae41d99892742b2da81
초기에 급하게 채워넣는다고 제대로 확인 안한 부분인 것 같습니다..! 말씀해주신 것 처럼 startAuth()나 showAuth() 등 해당 모듈에서 불필요한 기능들을 수정하였습니다!

2024-07-23 01:14 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Interface/Repository/AuthDataRepository.swift
> +  func appleLogin(token: String) -> Single<AuthTokenDTO>
저도 지연씨 생각과 같습니다~

2024-07-23 01:17 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +    return URL(string: "")!
현 상태로 가도 괜찮지 않을까 하는 생각입니다! 
생각보다 관련 공수가 꽤 있을 것 같은?

2024-07-23 01:20 UTC, usa4060 requested changes
추가 코멘트 남겼소

2024-07-23 01:20 UTC, usa4060 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthUsecase() -> AuthUseCase
다양한 기능이 존재함에 따라 usecase가 많아지는건 전혀 문제가 되지 않는다고 생각합니다~!
오히려, 구체적으로 나눔으로 인해서 코드 작성시의 가독성 혹은 테스트의 용이성이 증대된다면 더 장점이 많다고 생각해요

2024-07-23 01:20 UTC, usa4060 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +    return URL(string: "")!
현 상태유지로 가도 괜찮을 것 같아요!

2024-07-23 02:01 UTC, ji-yeon224 commented on WalWal/Coordinators/Auth/AuthCoordinator/Project.swift
> +let project = Project.invertedDualTargetProject(
https://github.com/depromeet/WalWal-iOS/pull/29/commits/c9a241d9058f5e9990329f83424c9f0a096f39a9
PR 참고해서 의존성 중복 부분 수정 완료하였습니다!

2024-07-23 02:33 UTC, ji-yeon224 commented on WalWal/DependencyFactory/Interface/DependencyFactory.swift
> +  func makeAuthUsecase() -> AuthUseCase
https://github.com/depromeet/WalWal-iOS/pull/29/commits/3c21f2d0a59c78ab1221b36912cc0616aa742d0d
넵! 해당 부분 AppleLoginUseCase로 변경하였습니다! 추후 usecase 생성시 기능별로 나눠 만들어보겠습니다~!

2024-07-23 02:34 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +      return "/auth/social-login/apple"
api 작업 시작하게 되었을 때 해당 내용 적용해보겠습니다~

2024-07-23 02:39 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthData/Implement/Endpoint/AuthEndpoint.swift
> +    return URL(string: "")!
/auth, /mission 과 같이 각 Endpoint마다 다르지만 내부에서는 공통으로 사용되는 경로가 있다면 그 또한 base url에 추가를 해야할 것 같아요! 헤더도 경로마다 변경될 수도 있을거라 생각해서 굳이 나눌 필요는 없을 것 같습니다~!

2024-07-23 02:52 UTC, ji-yeon224 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +  public func makeAuthData() -> AuthDataRepository {
stub repository라는 것이 AuthDataRepository 역할을 대체하는 별도의 클래스를 생성해서 가상의 데이터가 넘어왔다고 가정하여 플로우를 테스트하는 것이 맞나요?

2024-07-23 03:10 UTC, usa4060 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +  public func makeAuthData() -> AuthDataRepository {
옙 큰 의미는 그렇게 보면 됩니다~
미리 지정한 가짜 결과 값을 되돌려줌으로써 나머지 동작(이 경우에는 네트워크 이후 작업)을 진행 할 수 있도록 해준다고 생각하면 됩니당.
만약 실패케이스의 검증이 필요하면, 실패에 관한 결과를 return해주는 구현
만약 성공케이스의 검증이 필요하면, 성공에 관한 결과를 return해주는 구현을 해주면 됩니다~

사실 stub과 mock이 개념적으로 좀 다르긴 한데,,, 일단 대충 위와 같다고 생각하면 됩니다 ㅎ,,

2024-07-23 03:47 UTC, usa4060 approved these changes

2024-07-23 08:20 UTC, Zoe0929 approved these changes
고생하셨습니다~!

2024-07-23 08:30 UTC, merged