미션 시작 뷰 구현
depromeet/WalWal-iOS pull request #44
Opened 2024-07-27 11:18 UTC by Zoe0929

## 📌 개요
미션 시작 뷰 UI 구현했습니다. 

## ✍️ 변경사항
#### Adjust
현재 375*812 사이즈로 공유된 디자인을 기기대응하기 위해 비율에 맞게 조정하는 Extension을 추가했습니다. 추후 디자인팀에게 기기대응 가이드를 받은 후 다시 적용 예정입니다. (마찬가지로 hex code color 관련 extension도 이전 PR 머지 후 삭제 예정입니다)

## 📷 스크린샷
|SE|13 mini|15 pro|
|------|---|---|
|<img src = https://github.com/user-attachments/assets/ee3f2198-8d09-4be6-b949-3955bb0b54f1 width = "280px" />|<img src = https://github.com/user-attachments/assets/f6e327be-8840-4014-af26-7f46d7798bc1 width = "280px" />| <img src = https://github.com/user-attachments/assets/77d867a0-620e-4500-838f-e62f5465c113 width = "280px" />|

## 🛠️ **Technical Concerns(기술적 고민)**

2024-07-27 14:20 UTC, ji-yeon224 requested changes
고생하셨습니다~
이전에 잠깐 했던 이야기로는 DesignSystem 쪽에서는 Utility 모듈을 의존하지 않는 방향이 좋을 것 같다구 했던 것 같습니다! 이 부분에 대해서는 다시 확실하게 다같이 이야기 해보는게 좋을 것 같아요!

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor?.action.onNext(.loadMission)
이 코드가 뭘 의미하는걸까욤? 
가장 앞에 `reactor?`는 View 프로퍼티 내에 선언된 reactor 프로퍼티로 접근하는 걸까요?? 
뭔가 missionReactor에 액션을 보내는 것 같아보이는데 `viewDidLoad()`에서 reactor로 바로 접근해야하는 이유가 있을까요?
`.loadMission` action을 보내고 싶다면 bindAction() 내에 구현되어야 할 코드인것 같습니다!

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +      .flex
`.flex`까지는 한 줄에 써도 될 것 같습니다! `rootContatiner.flex` 이렇게요!!

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  public func bindEvent() {
bindEvent()는 밑에 extension에 포함시켜두 될것같아요! 사실상 View 프로퍼티와 관계는 없지만 같은 bind로 구분을 해놓는게 좋을 것 같다구 생각합니다!

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Utility/Sources/Adjusted+.swift
> +public extension Int {
요기 인덴트가 4칸인 것 같아요!!

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +      .subscribe(onNext: { [weak self] mission in
요거 `.subscribe(with: onNext: )`로 weak self 대체할 수 있지 않나용?!?

2024-07-27 14:20 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor.state.map { $0.mission }
요거 우리 `.map`부터 한 줄 넘겨서 쓰기로 했던 것 같슴다!

2024-07-27 16:30 UTC, usa4060 requested changes
고생했습니다~!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/DesignSystem/Project.swift
> +        .Utility
현재 Develop에는 Utility는 DesignSystem에서 제외 된 상태입니다
그리고, 기존에 Toast에 있는 Window관련 extension도 사용처가 DesignSystem 이외에는 없을 것 같다는 판단으로 DesignSystem으로 옮긴 상태에요.
관련 이야기 한 내용 iOS톡방에 있으니, 확인 해 봐도 좋을 것 같습니다~!

+ 추가적으로 이야기가 더 필요하면 논의해봐도 좋아요~

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionData/Implement/Repository/MissionRepositoryImp.swift
> +  public func getMissionInfo() -> RxSwift.Single<MissionInfoDTO> {
`RxSwift.Single` -> `Single`

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionData/Interface/Repository/MissionRepository.swift
> +  func getMissionInfo() -> Single<MissionInfoDTO>
갑자기 문득 생각났는데 
이런 함수이름 get이런 prefix 사용하지 말자고 이야기 나왔었던 것 같은데 맞을까용??
[함수 이름 컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#2-%ED%95%A8%EC%88%98)

(ㅋㅋ 저도 다 바꿔야겠네요)

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionData/Interface/Repository/MissionRepository.swift
> +  func getMissionInfo() -> Single<MissionInfoDTO>
@ji-yeon224 @kimkyunghun3 
이건 다같이 다시 한번 상기해서, 본인이 작성했던 코드들 수정해서 바로 pr올리는거 어때용

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionDomain/Implement/MissionUseCaseImp.swift
> +        MissionModel(title: $0.title,
[줄바꿈 컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#2-%EC%A4%84%EB%B0%94%EA%BF%88)
첫번째 파라미터 위치!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionDomain/Interface/Model/Mission.swift
> +  public init(title: String, isStartMission: Bool, imageURL: String, date: Int, backgroundColorCode: String) {
[줄바꿈 컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#2-%EC%A4%84%EB%B0%94%EA%BF%88)
이것도 파라미터 수에 따른 줄바꿈!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +    let mission = MissionModel(title: "반려동물과 함께\n산책한 사진을 찍어요",
줄바꿈 컨벤션!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Reactors/MissionReactorImp.swift
> +    return Observable.just(mission).delay(.seconds(1), scheduler: MainScheduler.instance)
이거 포함해서 전체적인 Rx 체이닝 컨벤션 확인 부탁드려용
[Rx컨벤션](https://github.com/depromeet/WalWal-iOS/wiki/%F0%9F%90%B6-WALWAL-Code-Convention#5%EF%B8%8F%E2%83%A3-rx-%EC%BB%A8%EB%B2%A4%EC%85%98)

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor?.action.onNext(.loadMission)
저도 지연이랑 같은 생각입니다!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +      .flex
오호 저도 참고할게요

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  public func bindEvent() {
@Zoe0929 @kimkyunghun3 
다들 지연이 생각에 동의하면, 앞으로 모두 싱크를 맞춰야 할 것 같아용
+ 현재 템플릿도 수정해야함

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor.state.map { $0.mission }
정확하게는 오퍼레이터 부터!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Coordinators/Mission/MissionCoordinator/Interface/MissionCoordinator.swift
> +public protocol MissionCoordinator: BaseCoordinator { }
여기
`public protocol MissionCoordinator: BaseCoordinator { }`
-> `public protocol MissionCoordinator: BaseCoordinator where Flow = MissionCoordinatorFlow{ }`

이렇게 제네릭타입 명시적으로 지정해여, 나중에 MissionCoordinator에서 해당 Flow를 찾을 수 있어요!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Coordinators/Mission/MissionCoordinator/Interface/MissionCoordinator.swift
> +public protocol MissionCoordinator: BaseCoordinator { }
관련해서도 iOS톡방에서  예전에 지연이랑 저랑 이야기했던 내용 있으니까, 히스토리 찾아보면 좋을 것 같아요!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Utility/Sources/Adjusted+.swift
> +//  Adjusted+.swift
파일이름이 `Adjusted+`인 이유가 있을까요??
나중에 `Int` / `Double` 등등 타입별로 더 추가될 수 있는 만큼
파일들을 `Int+` / `Double+` 이런식으로 아예 분리하는 건 어떨까요?!

2024-07-27 16:30 UTC, usa4060 commented on WalWal/Utility/Sources/Adjusted+.swift
> +//  Adjusted+.swift
아니면 추후에도 계속 비율로 디바이스 대응을 하게 되면, 디바이스별로 파일을 나누는 것두?!

2024-07-27 20:14 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +    reactor?.action.onNext(.loadMission)
아하! 저는 단순히 값이 잘 전달되는지 테스트하기 위해 이곳에 작성했었습니다.
bindAction으로 코드 이동하겠습니다!~

2024-07-27 20:15 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  public func bindEvent() {
저도 이거 템플릿 그대로 사용한거라 다른 bind는 Extension에 있는데 이것만 위에 있어서 궁금했어요! 따로 익스텐션으로 빼지 않은 이유가 있을까요 ?

2024-07-27 20:19 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionData/Interface/Repository/MissionRepository.swift
> +  func getMissionInfo() -> Single<MissionInfoDTO>
앗 네트워크 함수에서는 HTTP Method 종류를 앞에 붙이는 습관 때문에,, 수정하겠습니다!

2024-07-28 05:25 UTC, ji-yeon224 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  public func bindEvent() {
요거 처음 템플릿에서는 전부 extension으로 뺐었던걸루 기억하는데 구조가 바뀌면서 다 들어간 것 같더라구요?
개인적인 생각으로는 전부 extension으로 빼는 것이 좋을 것 같다고 생각해요~ 
`bindEvent()`가 Reactor와는 관계 없지만 그래도 성격이 비슷하다고 생각해서 `bind()` 메서드에서 호출하도록 사용했구 extension으로 같이 빼서 사용했었습니다!

혹 다른 의견이 있다면 환영입니당~

2024-07-28 06:33 UTC, usa4060 commented on WalWal/Features/Mission/MissionPresenter/Implement/Views/MissionViewImp.swift
> +  public func bindEvent() {
저는 괜찮은 것 같아요~! 
의견 모두 통일되면 extension으로 빼는걸루 템플릿 수정 부탁해용 
@Zoe0929

2024-07-28 07:20 UTC, Zoe0929 commented on WalWal/Utility/Sources/Adjusted+.swift
> +//  Adjusted+.swift
기기 대응이라는 한가지 역할을 수행하는 Extension이라 한 곳에 모아두는 것이 코드 보기에 더 편할 것 같아서 한 파일에 작성했습니다! 
남겨주신대로 Int, Double은 더 많은 함수들이 추가될 수 있을 것 같아서 파일 분리 하도록 하겠습니다~

2024-07-28 08:05 UTC, Zoe0929 commented on WalWal/Coordinators/Mission/MissionCoordinator/Interface/MissionCoordinator.swift
> +public protocol MissionCoordinator: BaseCoordinator { }
https://github.com/depromeet/WalWal-iOS/pull/44/commits/a2b79be3675dea9e301a76d53305e7ec5ee336f1 수정 완료했습니다

2024-07-28 08:05 UTC, Zoe0929 commented on WalWal/Features/Mission/MissionDomain/Implement/MissionUseCaseImp.swift
> +        MissionModel(title: $0.title,
[44b48ac](https://github.com/depromeet/WalWal-iOS/pull/44/commits/44b48ac64ccab8af32f91a971cfb4101aff0d6b7) 컨벤션 여기서 적용했습니다 ~

2024-07-28 08:26 UTC, closed without merging