인터셉터 구현
depromeet/WalWal-iOS pull request #65
Opened 2024-08-01 14:12 UTC by Zoe0929

## 📌 개요
네트워크 계층 내부에 interceptor 와 토큰 재발급 네트워크 통신 구현했습니다. 

## ✍️ 변경사항
소셜로그인 관련한 PR 머지 후 추가 구현 예정입니다. 
### retry( : )
- 서버 요청 실패 시 진입, ststus code에 따라 다른 처리 후 서버 재요청
>  ex. 401(인증 실패)의 경우 토큰 재발급 네트워크 연결 -> 토큰 재발급, 토큰 업데이트 -> 서버 재요청
### 애러 로깅 추가
- 서버 요청 실패 시 에러에 대해 print하는 과정을 추가했습니다.

## 📷 스크린샷
<img width="380" alt="image" src="https://github.com/user-attachments/assets/1d505c19-1fdf-4d6a-85ed-2e3e8f084d25">
- 현재 토큰 재발급 로직이 완성되지 않아 retry 진입하는 것만 확인했습니다. 

## 🛠️ **Technical Concerns(기술적 고민)**
- 토큰 재발급 네트워크에 대해 Data, Domain을 나누어 두었는데, 네트워크 모듈 내에서도 이렇게 나누어서 존재하는 게 맞는지 고민입니다. 
- 로그인 화면으로 돌아가기 위해서는 coorinator 단과 연결되어 있어야 할 것 같은데 이 부분을 어떻게 구현할지 고민해보겠습니다.

2024-08-01 14:53 UTC, ji-yeon224 approved these changes
고생하셨습니다! 
이렇게 구성하는게 맞는지는 잘 모르겠는데.. 로그인 요청해야할 경우 특정 에러를 `.doNotRetryWithError()`를 통해서 error 이벤트를 발생시키고 presenter단으로 돌아갔을 때 화면 이동 처리를 하도록 해야할 것 같다는 생각이 들었습니다! 화면 전환을 하려면 presenter로 돌아가야 할 것 같아요..!

2024-08-02 02:06 UTC, usa4060 commented
고생했어요~!
우선, 화면전환을 위한 처리의 경우는 지연씨가 말 한 것 처럼 `retry에서 에러나는 케이스`를 따로 지정해서, presenter단에서 코디네이터를 동작시키는게 맞는 플로우 입니다!

추가적으로, Network 모듈에서 따로 DTO나 Usecase Repository를 만드는건 올바른 형식이 아니라고 생각이 됩니다!
Network모듈은 의존성 구조 상 최하단에 위치하게 되는 모듈인데, 레이어를 만드는게 좀 어색하네요
오히려 직관적으로, raw한 코드로 작성하는게 좋을 것 같습니다

2024-08-02 02:07 UTC, usa4060 requested changes
고생했습니다~!
코멘트 확인하고 수정하는 방향으로!

2024-08-02 12:06 UTC, usa4060 commented
고생하셨습니다~

2024-08-02 12:06 UTC, usa4060 approved these changes
고생하셨습니다~

2024-08-03 07:50 UTC, merged