프로필 설정 뷰 구현
depromeet/WalWal-iOS pull request #78
Opened 2024-08-03 18:13 UTC by Zoe0929

## 📌 개요
프로필 설정 뷰 구현했습니다.

## ✍️ 변경사항
아직 데이터 바인딩 (버전 관련) 완료되지 않았습니다!

## 📷 스크린샷
<img src="https://github.com/user-attachments/assets/1770dd07-2765-4fbe-a990-1ae141a2492e" width = "300"/>

## 🛠️ **Technical Concerns(기술적 고민)**

2024-08-03 21:11 UTC, kimkyunghun3 requested changes
고생했습니다~!

2024-08-03 21:11 UTC, kimkyunghun3 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingTableViewCell.swift
> +  // MARK: - UI
MARK blank

2024-08-03 21:11 UTC, kimkyunghun3 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingTableViewCell.swift
> +  func configureCell(
cell인것을 알고 쓸거같아서 Cell naming 제거해두댈거같아요!

2024-08-03 21:11 UTC, kimkyunghun3 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +struct Setting {
View에 왜 모델이 있을까요~?

2024-08-03 21:11 UTC, kimkyunghun3 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +        cell.selectionStyle = .none
이 설정은 셀에서 하는게 맞는거같습니다~!

2024-08-04 10:43 UTC, ji-yeon224 approved these changes

2024-08-04 10:43 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +        .items(cellIdentifier: "ProfileSettingTableViewCell",
이거 어제 말한 것 처럼 Utility에 있는 UITableView Extension을 이용해서 identifier설정하고, rx extension 만들어서 사용하는 방식으로 변경해보는 것도 좋을 것 같습니다! UICollectionView Extension 참고헤보면 될 것 같아요~

2024-08-04 10:43 UTC, ji-yeon224 approved these changes
고생하셨습니다~

2024-08-05 11:10 UTC, ji-yeon224 requested changes
고생하셨습니다!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
> +          .map { Mutation.setAppVersion($0) },
`fetchAppVersion()`의 리턴 타입을 `Observable<Mutation>`으로 수정해보면 좋을 것 같아요!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
> +        Observable.just(.setLoading(true)),
크게 상관은 없지만 어차피 리턴 타입이 Observable이기 때문에 앞에 Observable을 명시하지 않아도 됩니다! 그냥 `.concat`, `.just`해도 됩니다~!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
> +      isRecent = currentVersion >= fetchedVersion
reduce()에서는 이전 state값을 새로운 값으로 리턴해주는 역할을 하기 때문에 로직을 통해 데이터를 만들어내는 작업은 mutate()에서 처리하는게 맞을 것 같아요! 
특별한 이유가 없다면 reduce에서는 mutate를 통해 받은 값을 `newState.setting = data`로 변경해주는 작업을 하는 것이 적절할 것 같습니다~

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/DataSource/ProfileSettingTableViewCell.swift
> +  // MARK: - UI
한 줄 띄우기!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/DataSource/ProfileSettingTableViewCell.swift
> +    containerView.pin.all()
.all()이랑 .layout() 줄 넘기기!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +  // MARK: - UI
마크 한 줄 띄우기!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +      .map { ProfileSettingReactorAction.viewDidLoad }
이거 View 프로퍼티에 typealias로 Reactor가 있을거에요! 그래서 `Reactor.Action.viewDidLoad`로 해도 됩니다!
그리고 액션 이름이 viewDidLoad여서 무슨 작업을 하는 액션인건지 잘 모르겠어요..! 좀 더 명확한 네이밍을 쓰는게 좋을 것 같습니다!

2024-08-05 11:10 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +    $0.register(ProfileSettingTableViewCell.self, forCellReuseIdentifier: "ProfileSettingTableViewCell")
register UITableView Extension에 구현된거 사용해도 될 것 같아요!

2024-08-05 17:25 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +        cell.selectionStyle = .none
위의 리뷰까지 반영 완료했습니다~

2024-08-06 01:25 UTC, kimkyunghun3 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +        cell.selectionStyle = .none
@Zoe0929  커밋좀 알려주세요! 반영된곳이 어딘지 찾기가 어렵군요..!

2024-08-06 05:47 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/ProfileSettingViewImp.swift
> +      .map { ProfileSettingReactorAction.viewDidLoad }
말그대로 뷰에 진입하자마자 일어나야 할 일들이라 `.viewDidLoad`로 네이밍하였습니다! 서버 통신으로 받아오는 요소들이 아니라 fetch라는 네이밍을 쓰는 게 조금 어색한데, 조금 더 고민해보겠습니다!

2024-08-06 07:16 UTC, usa4060 approved these changes
고생하셨습니다~
그런데, 코드 상으로는 아직 MyPage뷰에서의 화면전환은 안들어간 것 같은데
따로 추가하실건가요?? 아니면 제가 하면 될까여

2024-08-06 12:54 UTC, ji-yeon224 reviewed
고생하셨어요~

2024-08-06 12:54 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
> +    return Observable<Mutation>.create { observer in
요거 create로 만든 이유가 있나요?!?

2024-08-06 12:54 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/Extensions/UITableView+.swift
> +  /// 데이터 스트림을 UICollectionView에 바인딩
요거 주석 UITableView로 수정해주면 좋을 것 같습니다~

2024-08-06 13:50 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Reactors/ProfileSettingReactorImp.swift
> +    return Observable<Mutation>.create { observer in
concat으로 단순화해도 될 것 같네요! 수정 완료했습니다~

2024-08-06 15:41 UTC, ji-yeon224 approved these changes

2024-08-06 16:54 UTC, merged