소셜로그인 API 작업 및 화면 이동
depromeet/WalWal-iOS pull request #81
Opened 2024-08-05 08:58 UTC by ji-yeon224

## 📌 개요
소셜로그인 네트워크 통신 후 화면 이동 처리를 구현

## ✍️ 변경사항
- 카카오 로그인과 애플로그인 네트워크 통신을 구현하였습니다.
  - Domain Layer에 기존에 AppleLoginUseCase를 생성하여 사용했는데, 애플과 카카오 로그인이 거의 동일한 로직을 가지기 때문에 KakaoLoginUseCase를 별도로 가지는 것이 의미 없다 판단하여 SocialLoginUseCase로 변경하였습니다.
- 로그인 완료 후 임시토큰 여부에 따라 화면 이동을 구현하였습니다.
## 📷 스크린샷

| iPhone 15 pro | iPhone se3 |
| ---- | -- |
 | <img src = "https://github.com/user-attachments/assets/e721c072-fe0f-4d58-86e6-08ea3b4e7d5c" width="250px"> | <img src = "https://github.com/user-attachments/assets/58632bd2-da60-4cf9-b859-6dfaf01464a9" width = "250px"> |

https://github.com/user-attachments/assets/e47f49d6-881e-445b-ab20-a78f4479fbe3

## 🛠️ **Technical Concerns(기술적 고민)**
x

2024-08-05 17:21 UTC, Zoe0929 approved these changes
고생하셨습니다! baseurl은 Config파일로 옮기는 방법도 있을 것 같아요~! 네트워크 계층 수정하면서 제가 같이 작업하겠습니다!

2024-08-05 17:21 UTC, Zoe0929 commented on WalWal/DesignSystem/Sources/ActivityIndicator/ActivityIndicator.swift
> +    activityIndicator.pin.center().size(30)
여기 줄바꿈 필요할 것 같습니다!

2024-08-05 23:30 UTC, kimkyunghun3 approved these changes
고생해써요~ 
질문에 대한 저의 생각은 Utility로 뺴는건 적절하지 않는거같습니다
Utlity에서 써드파티 의존할 이유도 없고 사용처도 명확해서 말씀하신대로 LogOutmanager로 분리해서 해도될거같아요
로그아웃이나 회원탈퇴 기능이 근데 써드파티에서 해야할게있나요?

2024-08-06 01:37 UTC, ji-yeon224 commented
> 고생해써요~ 질문에 대한 저의 생각은 Utility로 뺴는건 적절하지 않는거같습니다 Utlity에서 써드파티 의존할 이유도 없고 사용처도 명확해서 말씀하신대로 LogOutmanager로 분리해서 해도될거같아요 로그아웃이나 회원탈퇴 기능이 근데 써드파티에서 해야할게있나요?

@kimkyunghun3 카카오 로그아웃 및 탈퇴의 경우에는 카카오 sdk가 필요합니다!

2024-08-06 01:51 UTC, usa4060 requested changes
우선 소셜로그인매니저는 유틸에 들어가지 않는게 맞는 것이라고 판단됩니다.
추가적으로, 로그아웃 및 탈퇴 메서드 또한 분리 할 필요는 없어 보이구요!

그 이유는, 결국 소셜 관련 [로그인, 로그아웃, 회원탈퇴] 로직은 모두 WalWal이 아닌 외부앱에 의존되어지는 형태이기 때문에 한번에 처리하는 단일 매니저를 구성하는게 더 좋은 방향이라는 생각이에요!

그리고 다른 모듈에서 회원탈퇴나 로그아웃을 하게 되는 경우는
이전 해커톤에서 말씀 드렸다시피, 어차피 실제 구현부는 앱 실행시 모두 생성하고 이후에는 모두 인터페이스로 추상화된 형태로 전달되게 됩니다.
따라서 필요하다면 authDependency에 대한 DependencyFactory 인터페이스를, 필요로하는 모듈의 Coordinator의 생성부에서 전달해주면 될 것 같아요!

구현하느라 고생했습니다~

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Views/AuthViewImp.swift
> +  typealias Color = ResourceKitAsset.Colors
접근제한자로 private 붙여봅시다

2024-08-06 01:51 UTC, usa4060 commented on WalWal/App/Sources/AppDelegate.swift
> +    KakaoSDK.initSDK(appKey: "29e3431e2dc66a607f511c0a05f0963b")
이것도 나중에는 전처리 하는 방식으로 수정합시다

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthDomain/Implement/SocialLoginUseCaseImp.swift
> +//  Created by Jiyeon on 8/1/24.
ㅋㅋㅋ 날짜 바꾼거 왤케 웃기지

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/DemoApp/Sources/AuthDemoAppDelegate.swift
> +//    let dependencyFactory = AuthDependencyFactoryImp()
이 코드들은 왜 다 날린건가여?

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        let _ = KeychainWrapper.shared.setAccessToken(result.accessToken)
이거 근데, isTemporaryToken이 true일 경우에는
키체인에 저장하면 안되는거 아닌가요???

이렇게 되면 소셜로그인만 성공 한 채로 앱 종료 후, 앱 재실행하면
메인화면으로 넘어가는 로직이 될 것 같아요

제가 이해한 바로는, 소셜로그인에 결과로 나오는 accessToken은 회원가입 API에만 사용하는 accessToken이라고 들어성

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Views/KakaoLoginManager.swift
> +//
별거 아니긴 한디, 매니저들은 폴더 따로 만들어서 넣어두는거 어떤가오

2024-08-06 01:51 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        return .concat([
이렇게 해두면, 소셜로그인 자체에서 발생하는 에러케이스도 전부 catch되는 것 맞을까요?
(단순 질문이니, 코멘트로만 말씀 해주세용!)

2024-08-06 01:51 UTC, usa4060 commented on WalWal/WalWalNetwork/Sources/Foundation/NetworkServiceImp.swift
> +    print(data)
테스트 완료 되었으면 제거하죵

2024-08-06 01:51 UTC, usa4060 commented on WalWal/WalWalNetwork/Sources/Foundation/WalwalInterceptor.swift
> +    print(statusCode)
마찬가지로 제거 하죵

2024-08-06 01:55 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthDomain/Implement/SocialLoginUseCaseImp.swift
> +//  Created by Jiyeon on 8/1/24.
뭐야 내가 안바꿔써.. 뭐지ㅋㅎ

2024-08-06 01:58 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/DemoApp/Sources/AuthDemoAppDelegate.swift
> +//    let dependencyFactory = AuthDependencyFactoryImp()
저거 상관은 없는데 demo 돌릴 때 parentCoordinator nil로 해야해서 dependencyfactory에 parentCoordinator를 옵셔널 타입으로 수정해서 사용하던 코드입니다. 왈왈을 돌리는건 문제 없는데 데모 빌드하면 저기서 오류떠서 그냥 막아뒀어용,,

2024-08-06 02:06 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        let _ = KeychainWrapper.shared.setAccessToken(result.accessToken)
앗 그 부분을 생각 못했네여..
근데 회원가입을 하려면 accessToken이 필요할거고, 네트워크 쪽에서는 키체인에 있는 accessToken을 가져와서 헤더에 넣을텐데 임시 토큰을 어떻게 관리해야할까용..

키체인에 임시 토큰인지 여부를 accessToken과 함께 저장하고, 종료 -> 재실행시 임시토큰 여부를 체크하는 방향으로 가야할까요?

2024-08-06 02:12 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        return .concat([
넵! WalWalNetwork request쪽에서 에러로 반환되는 경우는 저 부분에서 catch됩니다! 지금은 네트워크쪽에서 특정 경우 제외하고는 에러를 반환하지 않아서 수정이 필요한 상황입니다~

2024-08-06 02:20 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        let _ = KeychainWrapper.shared.setAccessToken(result.accessToken)
음 현재 상황에서는 그게 제일 간편할 것 같아요

키체인에 [accessToken / isTemporaryToken] 저장해두고, 
스플래시 단계에서 accessToken 확인 할 때 isTemporaryToken도 같이 확인하는 방식으로 해야겠어요

2024-08-06 02:43 UTC, usa4060 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        let _ = KeychainWrapper.shared.setAccessToken(result.accessToken)
아 근데 이러면, 인터셉터쪽 코드에서 isTemporaryToken이걸 또 세팅 해주고 해야할 것 같은데,,,,

그냥, NetworkService 함수 자체를 인터셉터 있는 request랑 인터셉터 없는 request로 분기처리 하는게 나을 것 같기도??
그러면 인터셉터 없는 request에서 그냥 accessToken을 header에 직접 넣어주면 되니까

2024-08-06 03:11 UTC, ji-yeon224 commented on WalWal/Features/Auth/AuthPresenter/Implement/Reactors/AuthReactorImp.swift
> +        let _ = KeychainWrapper.shared.setAccessToken(result.accessToken)
https://github.com/depromeet/WalWal-iOS/pull/81/commits/96cfc067aa5cac1cded0ee70ed4a19bde38dca31
UserDefaults로 임시 토큰 별도 저장으로 수정했습니다!

2024-08-06 03:18 UTC, usa4060 approved these changes
확인 했습니다~
AuthEndPoint 수정은, 지희가 NetworkService쪽 수정하면 적용하는걸루₩

2024-08-06 03:29 UTC, merged