WalWalButton 구현
depromeet/WalWal-iOS pull request #88
Opened 2024-08-07 05:11 UTC by usa4060

## 📌 개요
DesignSystem의 WalWalButton을 구현합니다.
## ✍️ 변경사항

## 📷 스크린샷
https://github.com/user-attachments/assets/6c721931-bc06-480f-91df-31102e7511d3

## 🛠️ **Technical Concerns(기술적 고민)**
### 사용 방법은, Demo코드 참고!

2024-08-07 05:43 UTC, ji-yeon224 reviewed
고생하셨습니다! 코멘트로 의견 하나 남겼습니다~

2024-08-07 05:43 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +    self.rootView.pin.all()
.all, .flex 줄바꿈!

2024-08-07 05:43 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButtonType.swift
> +public enum WalWalButtonType {
인덴트 4칸인거 같은데용!

2024-08-07 05:43 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +public final class WalWalButton: UIView {
버튼 뷰 의견이 하나 있습니다! 기존 UIButton()처럼 활성화 여부를 설정할 수 있는 isEnable 프로퍼티가 있으면 좋을 것 같아요! button.isEnable = false로 하면 버튼 액션 막히고, 백그라운드 컬러도 변경되는 프로퍼티가 있으면 좋겠어요~ true값 주면 다시 활성화가 되는 방식!

2024-08-07 05:43 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +    backgroundColor: UIColor
위에 코멘트에 남긴 것처럼 진행된다면 백그라운드 컬러는 활성화 색상으로 지정할 수 있을 것 같아요. 
그리고 활성화 된 백그라운드 컬러와 비활성화 백그라운드 컬러가 현재로는 다 같은 색이 사용되고 있는 것 같아서 해당 색상은 디폴트 값을 갖게 하고 필요한 경우에 별도 지정해서 사용하게 하는 것도 괜찮을 것 같습니다!

2024-08-07 05:45 UTC, usa4060 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +public final class WalWalButton: UIView {
아 생각해보니까 그걸 깜빡했네요 추가할게요~

2024-08-08 06:02 UTC, Zoe0929 approved these changes
고생하셨습니다~!

2024-08-08 22:44 UTC, usa4060 commented
@ji-yeon224  수정 완료~

2024-08-09 04:27 UTC, ji-yeon224 requested changes
저번에 컨벤션 관련 코멘트 남긴 부분 반영이 안된 것 같아요~ 확인 부탁드려요~

2024-08-09 04:27 UTC, ji-yeon224 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +  public init(
버튼 초기 설정에 디폴트로 색 속성이 들어가있으면 좋겠어요. 우리 서비스에서 대체로 활성화 시 오렌지 컬러가 사용되고 텍스트 컬러는 하얀색, 비활성화 시 백그라운드는 회색, 글자 색은 하얀색을 사용하고 있습니다! 
다른 컬러가 들어갈 경우가 생길 수도 있지만 다른 경우에만 지정할 수 있도록 하면 더 좋을 것 같아요. 현재 타이틀 컬러에 검정색을 기본으로 해놓으셨는데 저희 버튼 중에는 검정 텍스트컬러가 들어가는 경우가 일단은 없어서 기본 값으로 적절하지 않은 것 같아요!

2024-08-09 04:54 UTC, usa4060 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +  public init(
아 제가 state를 잘 못 이해했었네요!
Icon과 Normal이라는 상태로만 생각하고 있었는데, figma에서 다시 보니
Icon / Normal로 구분하면 안될 것 같네욥
수정하겠습니다~!

2024-08-09 18:23 UTC, usa4060 commented on WalWal/DesignSystem/Sources/WalWalButton/WalWalButton.swift
> +  public init(
@ji-yeon224 수정 했어요~

https://github.com/user-attachments/assets/a6b59cb5-f97d-4292-956f-4dc2a3c06878

2024-08-12 01:28 UTC, ji-yeon224 approved these changes
고생하셨어유~~

2024-08-12 02:48 UTC, merged