Feature/dependency factory module
depromeet/WalWal-iOS pull request #9
Opened 2024-07-11 02:21 UTC by usa4060

## 📌 개요
생성되는 다양한 모듈들의 중앙집중형 Dependency 관리를 위한 DependencyFactory 구현
## ✍️ 변경사항
DependencyFactory 초기 설계 및 예제코드 반영
## 📷 스크린샷

## 🛠️ **Technical Concerns(기술적 고민)**
- 모든 모듈을 한번에 관리하는 Factory를 사용할 지, Module별로 하위로 갖게되는 Dependency들만 관리하는 Factory단위로 나눠서 구현하는게 좋을 지 고민
- 현재 구현의 의도하는 바는, App최상단 (AppDelegate or SceneDelegate)에서 Factory를 생성 후, 이후 Module을 담당하게 될 Coordinator의 생성자로 주입하는 형식으로 1개의 Factory객체를 모든 Module에서 사용하고자 의도

> [!NOTE]
> [관련해서 고민들을 간단하게 끄적인 글](http://yongin9805.notion.site)

2024-07-11 05:54 UTC, kimkyunghun3 requested changes
설계해주시느냐고 고생했습니다 :)

2024-07-11 05:54 UTC, kimkyunghun3 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +import UIKit
요거랑 foundation 둘중 하나 필요한것만 남기면 조을거같아요~

2024-07-11 05:54 UTC, kimkyunghun3 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +/*
주석 방식은 /// 3개 사용하는거로 바꿔주면 좋을거같네요
그떄 주석 그렇게 하자고 했습니다!

2024-07-11 06:03 UTC, usa4060 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +import UIKit
옙 우선 UIKit만 남길게요~

2024-07-11 06:05 UTC, ji-yeon224 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +// Ex.
Feature 생성할 때 마다 이 곳에서 import와 생성 및 주입 코드를 작성하면 되는건가요?? 제가 이해한게 맞는지 확인차 질문드립니다~

2024-07-11 06:12 UTC, usa4060 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +/*
아, 요거는 아래내용 전부 주석처리 일괄로 하려고 /**/ 사용 했슴다!
앞으로 단일 주석은 모두 /// 사용할게요~
(다른 파일에서 단일 주석인데도 // 사용했던 기억이 나기도,,,ㅎ)

2024-07-11 06:14 UTC, usa4060 commented on WalWal/DependencyFactory/Implement/DependencyFactoryImp.swift
> +// Ex.
예 맞슴미다~

2024-07-11 06:17 UTC, ji-yeon224 approved these changes

2024-07-11 22:25 UTC, Zoe0929 approved these changes
고생하셨습니다!

2024-07-12 03:11 UTC, kimkyunghun3 approved these changes
확인요~

2024-07-12 03:13 UTC, merged