기록 상세 뷰 구현
depromeet/WalWal-iOS pull request #92
Opened 2024-08-07 10:07 UTC by Zoe0929

## 📌 개요
마이페이지 캘린더 셀 클릭 시 표출되는 기록 상세 뷰를 구현했습니다. 

## ✍️ 변경사항
화면 전환까지는 완료되었으나, 데이터 연결은 미완료 상태입니다. 
이어서 다음 이슈에서 진행하겠습니다!

## 📷 스크린샷
![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-08-07 at 18 38 02](https://github.com/user-attachments/assets/44ebdec4-cda8-4b3b-8102-35d8bc8fc5f0)

## 🛠️ **Technical Concerns(기술적 고민)**
WalWal로 빌드 시에는 캘린더 클릭 시 화면 전환이 잘 되는데, MypageDemoApp으로 빌드 시에는 화면전환이 이뤄지지 않습니다. 
이 경우, NavigationStack을 확인했을 때, 계속 쌓이기만 하고, 화면 상에는 보이지 않는 것을 확인했습니다. 
<img width="694" alt="image" src="https://github.com/user-attachments/assets/5580f8d1-453a-482a-aef2-82a420ca2dbe">

데모앱으로 빌드 시, TabBarViewController 가 아닌 MypageViewController가 root일 것이라 생각했는데, 빌드 후 바로 네이게이션 스택을 확인하면, 스택이 비어있는 걸 확인할 수 있었습니다. 그렇다면 화면 전환을 테스트할 때는 무조건 WalWal로 빌드해야하는 것인지, 탭바 대신 start의 VC을 루트로 사용할 수 없을지 궁금합니다!
<img width="677" alt="image" src="https://github.com/user-attachments/assets/d5d7fc1e-ae53-4599-b4d9-fb3a1b12c601">

2024-08-07 13:05 UTC, ji-yeon224 approved these changes
고생하셨습니다! 
데모 appdelegate에서 coordinator.start()하고, 루트 뷰컨을 coordinator.navigationController로 변경해도 안되려나요..? 요렇게 하면 저는 동작했던걸로 기억합니당..@

2024-08-07 13:05 UTC, ji-yeon224 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
> +        Reactor.Action.didSelectCalendarItem($0) }
줄바꿈이 요상해요~ 중괄호를 내리거나 모두 한 줄에 올리거나??

2024-08-07 13:06 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
> +        Reactor.Action.didSelectCalendarItem($0) }
진짜 왜 그랬지 수정하겠습니다요~!

2024-08-08 03:13 UTC, usa4060 commented
rootVC를 navigationViewController로 설정하면 동작 할거에용~
그리고 생각해보니까 캘린더에서 저 꽃 모양 위치 바꿔야하는데 깜빡하고 있었구만,,,

고생했습니다~

2024-08-08 03:22 UTC, usa4060 requested changes
코멘트 확인 부탁드려영

2024-08-08 03:22 UTC, usa4060 commented on WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
> +     let RecordDetailVC = myPageDependencyFactory.makeRecordDetailReactorViewController(reactor: reactor)
이거 근데 VC이름이 왜 `RecordDetailReactor` ViewController 인가여 ㅋㅋㅋㅋ?

2024-08-08 03:22 UTC, usa4060 commented on WalWal/DependencyFactory/MyPage/MyPageDependencyFactory/Interface/MyPageDependencyFactory.swift
> +  func makeRecordDetailReactorViewController<T: RecordDetailReactor>(reactor: T) -> any RecordDetailViewController
요기 이름도 뒤에 `makeRecordDetailReactorViewController` -> `makeRecordDetailViewController` 인 듯?

2024-08-08 03:22 UTC, usa4060 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
> +    bind()
근데 여기 `bind()`가, 예전에 [Reactor쪽 템플릿 만들었던 PR](https://github.com/depromeet/WalWal-iOS/pull/10#discussion_r1673505244)에서
하단의 `bindEvent()`로 네이밍 수정하고 위치를 옮기자고 해서 내려간거라 (Action과 State를 제외한 Reactive 동작)
없애도 됩니다

2024-08-08 05:09 UTC, Zoe0929 commented on WalWal/Coordinators/MyPage/MyPageCoordinator/Implement/MyPageCoordinatorImp.swift
> +     let RecordDetailVC = myPageDependencyFactory.makeRecordDetailReactorViewController(reactor: reactor)
오우 복붙 이슈가 있었네요 [40b6bf1](https://github.com/depromeet/WalWal-iOS/pull/92/commits/40b6bf11807aa4671c77051feeb12cc7dba1985f) 수정했습니다 ~ :3

2024-08-08 05:10 UTC, Zoe0929 commented on WalWal/Features/MyPage/MyPagePresenter/Implement/Views/MyPageViewImp.swift
> +    bind()
아하 그런 깊은 뜻이 ~ [08c4e87](https://github.com/depromeet/WalWal-iOS/pull/92/commits/08c4e87852590a0151ac6827f5aff5730d8b5646) 수정 완료입니다!

2024-08-08 09:56 UTC, usa4060 approved these changes
고생하셨습니다~

2024-08-08 12:43 UTC, merged